// @generated by cargo xtask slwl
#[rustfmt::skip]
static WORD_LISTS: &[&str] = &[
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-af"))]
    "aosp/af_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-ethi", feature = "lang-am"))]
    "aosp/am_Ethi.txt",
    #[cfg(any(feature = "aosp", feature = "script-arab", feature = "lang-ar"))]
    "aosp/ar_Arab.txt",
    #[cfg(any(feature = "aosp", feature = "script-beng", feature = "lang-as"))]
    "aosp/as_Beng.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-az"))]
    "aosp/az_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-be"))]
    "aosp/be_Cyrl.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-be"))]
    "aosp/be_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-bg"))]
    "aosp/bg_Cyrl.txt",
    #[cfg(any(feature = "aosp", feature = "script-beng", feature = "lang-bn"))]
    "aosp/bn_Beng.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-bs"))]
    "aosp/bs_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-ca"))]
    "aosp/ca_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-cs"))]
    "aosp/cs_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-da"))]
    "aosp/da_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-de"))]
    "aosp/de_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-grek", feature = "lang-el"))]
    "aosp/el_Grek.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-en"))]
    "aosp/en_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-es"))]
    "aosp/es_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-et"))]
    "aosp/et_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-eu"))]
    "aosp/eu_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-arab", feature = "lang-fa"))]
    "aosp/fa_Arab.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-fi"))]
    "aosp/fi_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-fr"))]
    "aosp/fr_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-gl"))]
    "aosp/gl_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-gujr", feature = "lang-gu"))]
    "aosp/gu_Gujr.txt",
    #[cfg(any(feature = "aosp", feature = "script-deva", feature = "lang-hi"))]
    "aosp/hi_Deva.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-hi"))]
    "aosp/hi_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-hr"))]
    "aosp/hr_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-hu"))]
    "aosp/hu_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-armn", feature = "lang-hy"))]
    "aosp/hy_Armn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-is"))]
    "aosp/is_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-it"))]
    "aosp/it_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-hira", feature = "lang-ja"))]
    "aosp/ja_Hira.txt",
    #[cfg(any(feature = "aosp", feature = "script-kana", feature = "lang-ja"))]
    "aosp/ja_Kana.txt",
    #[cfg(any(feature = "aosp", feature = "script-geor", feature = "lang-ka"))]
    "aosp/ka_Geor.txt",
    #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-kk"))]
    "aosp/kk_Cyrl.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-kk"))]
    "aosp/kk_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-khmr", feature = "lang-km"))]
    "aosp/km_Khmr.txt",
    #[cfg(any(feature = "aosp", feature = "script-knda", feature = "lang-kn"))]
    "aosp/kn_Knda.txt",
    #[cfg(any(feature = "aosp", feature = "script-hang", feature = "lang-ko"))]
    "aosp/ko_Hang.txt",
    #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-ky"))]
    "aosp/ky_Cyrl.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-ky"))]
    "aosp/ky_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-laoo", feature = "lang-lo"))]
    "aosp/lo_Laoo.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-lt"))]
    "aosp/lt_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-lv"))]
    "aosp/lv_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-mk"))]
    "aosp/mk_Cyrl.txt",
    #[cfg(any(feature = "aosp", feature = "script-mlym", feature = "lang-ml"))]
    "aosp/ml_Mlym.txt",
    #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-mn"))]
    "aosp/mn_Cyrl.txt",
    #[cfg(any(feature = "aosp", feature = "script-deva", feature = "lang-mr"))]
    "aosp/mr_Deva.txt",
    #[cfg(any(feature = "aosp", feature = "lang-ms"))]
    "aosp/ms.txt",
    #[cfg(any(feature = "aosp", feature = "script-mymr", feature = "lang-my"))]
    "aosp/my_Mymr.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-nb"))]
    "aosp/nb_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-deva", feature = "lang-ne"))]
    "aosp/ne_Deva.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-nl"))]
    "aosp/nl_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-orya", feature = "lang-or"))]
    "aosp/or_Orya.txt",
    #[cfg(any(feature = "aosp", feature = "script-guru", feature = "lang-pa"))]
    "aosp/pa_Guru.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-pl"))]
    "aosp/pl_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-pt"))]
    "aosp/pt_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-rm"))]
    "aosp/rm_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-ro"))]
    "aosp/ro_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-ru"))]
    "aosp/ru_Cyrl.txt",
    #[cfg(any(feature = "aosp", feature = "script-sinh", feature = "lang-si"))]
    "aosp/si_Sinh.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sk"))]
    "aosp/sk_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sl"))]
    "aosp/sl_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sq"))]
    "aosp/sq_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-sr"))]
    "aosp/sr_Cyrl.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sr"))]
    "aosp/sr_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sv"))]
    "aosp/sv_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sw"))]
    "aosp/sw_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-taml", feature = "lang-ta"))]
    "aosp/ta_Taml.txt",
    #[cfg(any(feature = "aosp", feature = "script-telu", feature = "lang-te"))]
    "aosp/te_Telu.txt",
    #[cfg(any(feature = "aosp", feature = "script-thai", feature = "lang-th"))]
    "aosp/th_Thai.txt",
    #[cfg(any(feature = "aosp", feature = "lang-tl"))]
    "aosp/tl.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-tr"))]
    "aosp/tr_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-uk"))]
    "aosp/uk_Cyrl.txt",
    #[cfg(any(feature = "aosp", feature = "script-arab", feature = "lang-ur"))]
    "aosp/ur_Arab.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-uz"))]
    "aosp/uz_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-vi"))]
    "aosp/vi_Latn.txt",
    #[cfg(any(feature = "aosp", feature = "script-hani", feature = "lang-zh"))]
    "aosp/zh_Hani.txt",
    #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-zu"))]
    "aosp/zu_Latn.txt",
    #[cfg(any(feature = "diffenator", feature = "script-adlm"))]
    "diffenator/Adlam.txt",
    #[cfg(any(feature = "diffenator", feature = "script-arab"))]
    "diffenator/Arabic.txt",
    #[cfg(any(feature = "diffenator", feature = "script-armn"))]
    "diffenator/Armenian.txt",
    #[cfg(any(feature = "diffenator", feature = "script-avst"))]
    "diffenator/Avestan.txt",
    #[cfg(any(feature = "diffenator", feature = "script-beng"))]
    "diffenator/Bengali.txt",
    #[cfg(any(feature = "diffenator", feature = "script-bopo"))]
    "diffenator/Bopomofo.txt",
    #[cfg(any(feature = "diffenator", feature = "script-cans"))]
    "diffenator/Canadian_Aboriginal.txt",
    #[cfg(any(feature = "diffenator", feature = "script-cakm"))]
    "diffenator/Chakma.txt",
    #[cfg(any(feature = "diffenator", feature = "script-cher"))]
    "diffenator/Cherokee.txt",
    #[cfg(any(feature = "diffenator", feature = "script-zyyy"))]
    "diffenator/Common.txt",
    #[cfg(any(feature = "diffenator", feature = "script-cyrl"))]
    "diffenator/Cyrillic.txt",
    #[cfg(any(feature = "diffenator", feature = "script-deva"))]
    "diffenator/Devanagari.txt",
    #[cfg(any(feature = "diffenator", feature = "script-ethi"))]
    "diffenator/Ethiopic.txt",
    #[cfg(any(feature = "diffenator", feature = "script-geor"))]
    "diffenator/Georgian.txt",
    #[cfg(any(feature = "diffenator", feature = "script-grek"))]
    "diffenator/Greek.txt",
    #[cfg(any(feature = "diffenator", feature = "script-gujr"))]
    "diffenator/Gujarati.txt",
    #[cfg(any(feature = "diffenator", feature = "script-guru"))]
    "diffenator/Gurmukhi.txt",
    #[cfg(any(feature = "diffenator", feature = "script-hebr"))]
    "diffenator/Hebrew.txt",
    #[cfg(any(feature = "diffenator", feature = "script-hira"))]
    "diffenator/Hiragana.txt",
    #[cfg(any(feature = "diffenator", feature = "script-jpan"))]
    "diffenator/Japanese.txt",
    #[cfg(any(feature = "diffenator", feature = "script-kana"))]
    "diffenator/Katakana.txt",
    #[cfg(any(feature = "diffenator", feature = "script-khmr"))]
    "diffenator/Khmer.txt",
    #[cfg(any(feature = "diffenator", feature = "script-laoo"))]
    "diffenator/Lao.txt",
    #[cfg(any(feature = "diffenator", feature = "script-latn"))]
    "diffenator/Latin.txt",
    #[cfg(any(feature = "diffenator", feature = "script-lisu"))]
    "diffenator/Lisu.txt",
    #[cfg(any(feature = "diffenator", feature = "script-mlym"))]
    "diffenator/Malayalam.txt",
    #[cfg(any(feature = "diffenator", feature = "script-mong"))]
    "diffenator/Mongolian.txt",
    #[cfg(any(feature = "diffenator", feature = "script-mymr"))]
    "diffenator/Myanmar.txt",
    #[cfg(any(feature = "diffenator", feature = "script-olck"))]
    "diffenator/Ol_Chiki.txt",
    #[cfg(any(feature = "diffenator", feature = "script-orya"))]
    "diffenator/Oriya.txt",
    #[cfg(any(feature = "diffenator", feature = "script-osge"))]
    "diffenator/Osage.txt",
    #[cfg(any(feature = "diffenator", feature = "script-sinh"))]
    "diffenator/Sinhala.txt",
    #[cfg(any(feature = "diffenator", feature = "script-syrc"))]
    "diffenator/Syriac.txt",
    #[cfg(any(feature = "diffenator", feature = "script-taml"))]
    "diffenator/Tamil.txt",
    #[cfg(any(feature = "diffenator", feature = "script-telu"))]
    "diffenator/Telugu.txt",
    #[cfg(any(feature = "diffenator", feature = "script-thai"))]
    "diffenator/Thai.txt",
    #[cfg(any(feature = "diffenator", feature = "script-thaa"))]
    "diffenator/Thanaa.txt",
    #[cfg(any(feature = "diffenator", feature = "script-tibt"))]
    "diffenator/Tibetan.txt",
    #[cfg(any(feature = "diffenator", feature = "script-tfng"))]
    "diffenator/Tifinagh.txt",
    #[cfg(any(feature = "diffenator", feature = "script-vaii"))]
    "diffenator/Vai.txt",
    #[cfg(any(feature = "ucd", feature = "script-zyyy"))]
    "ucd/Emoji_All.txt",
    #[cfg(any(feature = "ucd", feature = "script-zyyy"))]
    "ucd/Emoji_Color.txt",
    #[cfg(any(feature = "ucd", feature = "script-zyyy"))]
    "ucd/Emoji_Textual.txt",
];
