// @generated by egg.py
static WORD_LISTS: &[(&str, &str)] = &[
    (r"DiffenatorCyrillic", r"diffenator/Cyrillic.txt"),
    (r"DiffenatorGreek", r"diffenator/Greek.txt"),
    (r"DiffenatorLatin", r"diffenator/Latin.txt"),
];
