// @generated by cargo xtask egg
#[rustfmt::skip]
#[derive(Debug, Copy, Clone)]
struct WordListDecl {
    name: &'static str,
    ident: &'static str,
    rel_path: &'static str,
    metadata_decl: &'static str,
    features_attr: &'static str,
}
#[rustfmt::skip]
static WORD_LISTS: &[WordListDecl] = &[
    WordListDecl {
        name: "aosp_afrikaans_latin",
        ident: "AOSP_AFRIKAANS_LATIN",
        rel_path: "aosp/af_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_afrikaans_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("af")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-af",))]
        ),
    },
    WordListDecl {
        name: "aosp_amharic_ethiopic",
        ident: "AOSP_AMHARIC_ETHIOPIC",
        rel_path: "aosp/am_Ethi.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_amharic_ethiopic"), script :
            Some(std::borrow::Cow::Borrowed("Ethi")), language :
            Some(std::borrow::Cow::Borrowed("am")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-ethi", feature = "lang-am",))]
        ),
    },
    WordListDecl {
        name: "aosp_arabic",
        ident: "AOSP_ARABIC",
        rel_path: "aosp/ar_Arab.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_arabic"),
            script : Some(std::borrow::Cow::Borrowed("Arab")), language :
            Some(std::borrow::Cow::Borrowed("ar")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-arab", feature = "lang-ar",))]
        ),
    },
    WordListDecl {
        name: "aosp_assamese_bengali",
        ident: "AOSP_ASSAMESE_BENGALI",
        rel_path: "aosp/as_Beng.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_assamese_bengali"), script :
            Some(std::borrow::Cow::Borrowed("Beng")), language :
            Some(std::borrow::Cow::Borrowed("as")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-beng", feature = "lang-as",))]
        ),
    },
    WordListDecl {
        name: "aosp_azerbaijani_latin",
        ident: "AOSP_AZERBAIJANI_LATIN",
        rel_path: "aosp/az_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_azerbaijani_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("az")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-az",))]
        ),
    },
    WordListDecl {
        name: "aosp_belarusian_cyrillic",
        ident: "AOSP_BELARUSIAN_CYRILLIC",
        rel_path: "aosp/be_Cyrl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_belarusian_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language :
            Some(std::borrow::Cow::Borrowed("be")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-be",))]
        ),
    },
    WordListDecl {
        name: "aosp_belarusian_latin",
        ident: "AOSP_BELARUSIAN_LATIN",
        rel_path: "aosp/be_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_belarusian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("be")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-be",))]
        ),
    },
    WordListDecl {
        name: "aosp_bulgarian_cyrillic",
        ident: "AOSP_BULGARIAN_CYRILLIC",
        rel_path: "aosp/bg_Cyrl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_bulgarian_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language :
            Some(std::borrow::Cow::Borrowed("bg")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-bg",))]
        ),
    },
    WordListDecl {
        name: "aosp_bengali",
        ident: "AOSP_BENGALI",
        rel_path: "aosp/bn_Beng.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_bengali"),
            script : Some(std::borrow::Cow::Borrowed("Beng")), language :
            Some(std::borrow::Cow::Borrowed("bn")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-beng", feature = "lang-bn",))]
        ),
    },
    WordListDecl {
        name: "aosp_bosnian_latin",
        ident: "AOSP_BOSNIAN_LATIN",
        rel_path: "aosp/bs_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_bosnian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("bs")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-bs",))]
        ),
    },
    WordListDecl {
        name: "aosp_catalan_latin",
        ident: "AOSP_CATALAN_LATIN",
        rel_path: "aosp/ca_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_catalan_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("ca")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-ca",))]
        ),
    },
    WordListDecl {
        name: "aosp_czech_latin",
        ident: "AOSP_CZECH_LATIN",
        rel_path: "aosp/cs_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_czech_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("cs")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-cs",))]
        ),
    },
    WordListDecl {
        name: "aosp_danish_latin",
        ident: "AOSP_DANISH_LATIN",
        rel_path: "aosp/da_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_danish_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("da")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-da",))]
        ),
    },
    WordListDecl {
        name: "aosp_german_latin",
        ident: "AOSP_GERMAN_LATIN",
        rel_path: "aosp/de_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_german_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("de")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-de",))]
        ),
    },
    WordListDecl {
        name: "aosp_modern_greek",
        ident: "AOSP_MODERN_GREEK",
        rel_path: "aosp/el_Grek.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_modern_greek"), script :
            Some(std::borrow::Cow::Borrowed("Grek")), language :
            Some(std::borrow::Cow::Borrowed("el")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-grek", feature = "lang-el",))]
        ),
    },
    WordListDecl {
        name: "aosp_english_latin",
        ident: "AOSP_ENGLISH_LATIN",
        rel_path: "aosp/en_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_english_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("en")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-en",))]
        ),
    },
    WordListDecl {
        name: "aosp_spanish_latin",
        ident: "AOSP_SPANISH_LATIN",
        rel_path: "aosp/es_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_spanish_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("es")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-es",))]
        ),
    },
    WordListDecl {
        name: "aosp_estonian_latin",
        ident: "AOSP_ESTONIAN_LATIN",
        rel_path: "aosp/et_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_estonian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("et")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-et",))]
        ),
    },
    WordListDecl {
        name: "aosp_basque_latin",
        ident: "AOSP_BASQUE_LATIN",
        rel_path: "aosp/eu_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_basque_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("eu")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-eu",))]
        ),
    },
    WordListDecl {
        name: "aosp_persian_arabic",
        ident: "AOSP_PERSIAN_ARABIC",
        rel_path: "aosp/fa_Arab.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_persian_arabic"), script :
            Some(std::borrow::Cow::Borrowed("Arab")), language :
            Some(std::borrow::Cow::Borrowed("fa")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-arab", feature = "lang-fa",))]
        ),
    },
    WordListDecl {
        name: "aosp_finnish_latin",
        ident: "AOSP_FINNISH_LATIN",
        rel_path: "aosp/fi_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_finnish_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("fi")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-fi",))]
        ),
    },
    WordListDecl {
        name: "aosp_french_latin",
        ident: "AOSP_FRENCH_LATIN",
        rel_path: "aosp/fr_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_french_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("fr")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-fr",))]
        ),
    },
    WordListDecl {
        name: "aosp_galician_latin",
        ident: "AOSP_GALICIAN_LATIN",
        rel_path: "aosp/gl_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_galician_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("gl")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-gl",))]
        ),
    },
    WordListDecl {
        name: "aosp_gujarati",
        ident: "AOSP_GUJARATI",
        rel_path: "aosp/gu_Gujr.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_gujarati"), script :
            Some(std::borrow::Cow::Borrowed("Gujr")), language :
            Some(std::borrow::Cow::Borrowed("gu")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-gujr", feature = "lang-gu",))]
        ),
    },
    WordListDecl {
        name: "aosp_hindi_devanagari",
        ident: "AOSP_HINDI_DEVANAGARI",
        rel_path: "aosp/hi_Deva.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_hindi_devanagari"), script :
            Some(std::borrow::Cow::Borrowed("Deva")), language :
            Some(std::borrow::Cow::Borrowed("hi")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-deva", feature = "lang-hi",))]
        ),
    },
    WordListDecl {
        name: "aosp_hindi_latin",
        ident: "AOSP_HINDI_LATIN",
        rel_path: "aosp/hi_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_hindi_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("hi")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-hi",))]
        ),
    },
    WordListDecl {
        name: "aosp_croatian_latin",
        ident: "AOSP_CROATIAN_LATIN",
        rel_path: "aosp/hr_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_croatian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("hr")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-hr",))]
        ),
    },
    WordListDecl {
        name: "aosp_hungarian_latin",
        ident: "AOSP_HUNGARIAN_LATIN",
        rel_path: "aosp/hu_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_hungarian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("hu")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-hu",))]
        ),
    },
    WordListDecl {
        name: "aosp_armenian",
        ident: "AOSP_ARMENIAN",
        rel_path: "aosp/hy_Armn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_armenian"), script :
            Some(std::borrow::Cow::Borrowed("Armn")), language :
            Some(std::borrow::Cow::Borrowed("hy")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-armn", feature = "lang-hy",))]
        ),
    },
    WordListDecl {
        name: "aosp_icelandic_latin",
        ident: "AOSP_ICELANDIC_LATIN",
        rel_path: "aosp/is_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_icelandic_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("is")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-is",))]
        ),
    },
    WordListDecl {
        name: "aosp_italian_latin",
        ident: "AOSP_ITALIAN_LATIN",
        rel_path: "aosp/it_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_italian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("it")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-it",))]
        ),
    },
    WordListDecl {
        name: "aosp_japanese_hiragana",
        ident: "AOSP_JAPANESE_HIRAGANA",
        rel_path: "aosp/ja_Hira.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_japanese_hiragana"), script :
            Some(std::borrow::Cow::Borrowed("Hira")), language :
            Some(std::borrow::Cow::Borrowed("ja")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-hira", feature = "lang-ja",))]
        ),
    },
    WordListDecl {
        name: "aosp_japanese_katakana",
        ident: "AOSP_JAPANESE_KATAKANA",
        rel_path: "aosp/ja_Kana.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_japanese_katakana"), script :
            Some(std::borrow::Cow::Borrowed("Kana")), language :
            Some(std::borrow::Cow::Borrowed("ja")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-kana", feature = "lang-ja",))]
        ),
    },
    WordListDecl {
        name: "aosp_georgian",
        ident: "AOSP_GEORGIAN",
        rel_path: "aosp/ka_Geor.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_georgian"), script :
            Some(std::borrow::Cow::Borrowed("Geor")), language :
            Some(std::borrow::Cow::Borrowed("ka")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-geor", feature = "lang-ka",))]
        ),
    },
    WordListDecl {
        name: "aosp_kazakh_cyrillic",
        ident: "AOSP_KAZAKH_CYRILLIC",
        rel_path: "aosp/kk_Cyrl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_kazakh_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language :
            Some(std::borrow::Cow::Borrowed("kk")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-kk",))]
        ),
    },
    WordListDecl {
        name: "aosp_kazakh_latin",
        ident: "AOSP_KAZAKH_LATIN",
        rel_path: "aosp/kk_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_kazakh_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("kk")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-kk",))]
        ),
    },
    WordListDecl {
        name: "aosp_central_khmer",
        ident: "AOSP_CENTRAL_KHMER",
        rel_path: "aosp/km_Khmr.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_central_khmer"), script :
            Some(std::borrow::Cow::Borrowed("Khmr")), language :
            Some(std::borrow::Cow::Borrowed("km")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-khmr", feature = "lang-km",))]
        ),
    },
    WordListDecl {
        name: "aosp_kannada",
        ident: "AOSP_KANNADA",
        rel_path: "aosp/kn_Knda.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_kannada"),
            script : Some(std::borrow::Cow::Borrowed("Knda")), language :
            Some(std::borrow::Cow::Borrowed("kn")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-knda", feature = "lang-kn",))]
        ),
    },
    WordListDecl {
        name: "aosp_korean_hangul",
        ident: "AOSP_KOREAN_HANGUL",
        rel_path: "aosp/ko_Hang.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_korean_hangul"), script :
            Some(std::borrow::Cow::Borrowed("Hang")), language :
            Some(std::borrow::Cow::Borrowed("ko")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-hang", feature = "lang-ko",))]
        ),
    },
    WordListDecl {
        name: "aosp_kirghiz_cyrillic",
        ident: "AOSP_KIRGHIZ_CYRILLIC",
        rel_path: "aosp/ky_Cyrl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_kirghiz_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language :
            Some(std::borrow::Cow::Borrowed("ky")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-ky",))]
        ),
    },
    WordListDecl {
        name: "aosp_kirghiz_latin",
        ident: "AOSP_KIRGHIZ_LATIN",
        rel_path: "aosp/ky_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_kirghiz_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("ky")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-ky",))]
        ),
    },
    WordListDecl {
        name: "aosp_lao",
        ident: "AOSP_LAO",
        rel_path: "aosp/lo_Laoo.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_lao"),
            script : Some(std::borrow::Cow::Borrowed("Laoo")), language :
            Some(std::borrow::Cow::Borrowed("lo")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-laoo", feature = "lang-lo",))]
        ),
    },
    WordListDecl {
        name: "aosp_lithuanian_latin",
        ident: "AOSP_LITHUANIAN_LATIN",
        rel_path: "aosp/lt_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_lithuanian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("lt")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-lt",))]
        ),
    },
    WordListDecl {
        name: "aosp_latvian_latin",
        ident: "AOSP_LATVIAN_LATIN",
        rel_path: "aosp/lv_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_latvian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("lv")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-lv",))]
        ),
    },
    WordListDecl {
        name: "aosp_macedonian_cyrillic",
        ident: "AOSP_MACEDONIAN_CYRILLIC",
        rel_path: "aosp/mk_Cyrl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_macedonian_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language :
            Some(std::borrow::Cow::Borrowed("mk")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-mk",))]
        ),
    },
    WordListDecl {
        name: "aosp_malayalam",
        ident: "AOSP_MALAYALAM",
        rel_path: "aosp/ml_Mlym.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_malayalam"), script :
            Some(std::borrow::Cow::Borrowed("Mlym")), language :
            Some(std::borrow::Cow::Borrowed("ml")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-mlym", feature = "lang-ml",))]
        ),
    },
    WordListDecl {
        name: "aosp_mongolian_cyrillic",
        ident: "AOSP_MONGOLIAN_CYRILLIC",
        rel_path: "aosp/mn_Cyrl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_mongolian_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language :
            Some(std::borrow::Cow::Borrowed("mn")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-mn",))]
        ),
    },
    WordListDecl {
        name: "aosp_marathi_devanagari",
        ident: "AOSP_MARATHI_DEVANAGARI",
        rel_path: "aosp/mr_Deva.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_marathi_devanagari"), script :
            Some(std::borrow::Cow::Borrowed("Deva")), language :
            Some(std::borrow::Cow::Borrowed("mr")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-deva", feature = "lang-mr",))]
        ),
    },
    WordListDecl {
        name: "aosp_malay",
        ident: "AOSP_MALAY",
        rel_path: "aosp/ms.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_malay"),
            script : None, language : Some(std::borrow::Cow::Borrowed("ms")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "lang-ms",))]
        ),
    },
    WordListDecl {
        name: "aosp_burmese_myanmar",
        ident: "AOSP_BURMESE_MYANMAR",
        rel_path: "aosp/my_Mymr.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_burmese_myanmar"), script :
            Some(std::borrow::Cow::Borrowed("Mymr")), language :
            Some(std::borrow::Cow::Borrowed("my")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-mymr", feature = "lang-my",))]
        ),
    },
    WordListDecl {
        name: "aosp_norwegian_bokmål_latin",
        ident: "AOSP_NORWEGIAN_BOKMÅL_LATIN",
        rel_path: "aosp/nb_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_norwegian_bokmål_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("nb")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-nb",))]
        ),
    },
    WordListDecl {
        name: "aosp_nepali_devanagari",
        ident: "AOSP_NEPALI_DEVANAGARI",
        rel_path: "aosp/ne_Deva.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_nepali_devanagari"), script :
            Some(std::borrow::Cow::Borrowed("Deva")), language :
            Some(std::borrow::Cow::Borrowed("ne")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-deva", feature = "lang-ne",))]
        ),
    },
    WordListDecl {
        name: "aosp_dutch_latin",
        ident: "AOSP_DUTCH_LATIN",
        rel_path: "aosp/nl_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_dutch_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("nl")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-nl",))]
        ),
    },
    WordListDecl {
        name: "aosp_oriya",
        ident: "AOSP_ORIYA",
        rel_path: "aosp/or_Orya.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_oriya"),
            script : Some(std::borrow::Cow::Borrowed("Orya")), language :
            Some(std::borrow::Cow::Borrowed("or")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-orya", feature = "lang-or",))]
        ),
    },
    WordListDecl {
        name: "aosp_panjabi_gurmukhi",
        ident: "AOSP_PANJABI_GURMUKHI",
        rel_path: "aosp/pa_Guru.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_panjabi_gurmukhi"), script :
            Some(std::borrow::Cow::Borrowed("Guru")), language :
            Some(std::borrow::Cow::Borrowed("pa")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-guru", feature = "lang-pa",))]
        ),
    },
    WordListDecl {
        name: "aosp_polish_latin",
        ident: "AOSP_POLISH_LATIN",
        rel_path: "aosp/pl_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_polish_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("pl")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-pl",))]
        ),
    },
    WordListDecl {
        name: "aosp_portuguese_latin",
        ident: "AOSP_PORTUGUESE_LATIN",
        rel_path: "aosp/pt_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_portuguese_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("pt")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-pt",))]
        ),
    },
    WordListDecl {
        name: "aosp_romansh_latin",
        ident: "AOSP_ROMANSH_LATIN",
        rel_path: "aosp/rm_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_romansh_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("rm")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-rm",))]
        ),
    },
    WordListDecl {
        name: "aosp_romanian_latin",
        ident: "AOSP_ROMANIAN_LATIN",
        rel_path: "aosp/ro_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_romanian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("ro")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-ro",))]
        ),
    },
    WordListDecl {
        name: "aosp_russian_cyrillic",
        ident: "AOSP_RUSSIAN_CYRILLIC",
        rel_path: "aosp/ru_Cyrl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_russian_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language :
            Some(std::borrow::Cow::Borrowed("ru")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-ru",))]
        ),
    },
    WordListDecl {
        name: "aosp_sinhala",
        ident: "AOSP_SINHALA",
        rel_path: "aosp/si_Sinh.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_sinhala"),
            script : Some(std::borrow::Cow::Borrowed("Sinh")), language :
            Some(std::borrow::Cow::Borrowed("si")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-sinh", feature = "lang-si",))]
        ),
    },
    WordListDecl {
        name: "aosp_slovak_latin",
        ident: "AOSP_SLOVAK_LATIN",
        rel_path: "aosp/sk_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_slovak_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("sk")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sk",))]
        ),
    },
    WordListDecl {
        name: "aosp_slovenian_latin",
        ident: "AOSP_SLOVENIAN_LATIN",
        rel_path: "aosp/sl_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_slovenian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("sl")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sl",))]
        ),
    },
    WordListDecl {
        name: "aosp_albanian_latin",
        ident: "AOSP_ALBANIAN_LATIN",
        rel_path: "aosp/sq_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_albanian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("sq")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sq",))]
        ),
    },
    WordListDecl {
        name: "aosp_serbian_cyrillic",
        ident: "AOSP_SERBIAN_CYRILLIC",
        rel_path: "aosp/sr_Cyrl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_serbian_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language :
            Some(std::borrow::Cow::Borrowed("sr")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-sr",))]
        ),
    },
    WordListDecl {
        name: "aosp_serbian_latin",
        ident: "AOSP_SERBIAN_LATIN",
        rel_path: "aosp/sr_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_serbian_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("sr")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sr",))]
        ),
    },
    WordListDecl {
        name: "aosp_swedish_latin",
        ident: "AOSP_SWEDISH_LATIN",
        rel_path: "aosp/sv_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_swedish_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("sv")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sv",))]
        ),
    },
    WordListDecl {
        name: "aosp_swahili_latin",
        ident: "AOSP_SWAHILI_LATIN",
        rel_path: "aosp/sw_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_swahili_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("sw")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-sw",))]
        ),
    },
    WordListDecl {
        name: "aosp_tamil",
        ident: "AOSP_TAMIL",
        rel_path: "aosp/ta_Taml.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_tamil"),
            script : Some(std::borrow::Cow::Borrowed("Taml")), language :
            Some(std::borrow::Cow::Borrowed("ta")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-taml", feature = "lang-ta",))]
        ),
    },
    WordListDecl {
        name: "aosp_telugu",
        ident: "AOSP_TELUGU",
        rel_path: "aosp/te_Telu.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_telugu"),
            script : Some(std::borrow::Cow::Borrowed("Telu")), language :
            Some(std::borrow::Cow::Borrowed("te")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-telu", feature = "lang-te",))]
        ),
    },
    WordListDecl {
        name: "aosp_thai",
        ident: "AOSP_THAI",
        rel_path: "aosp/th_Thai.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_thai"),
            script : Some(std::borrow::Cow::Borrowed("Thai")), language :
            Some(std::borrow::Cow::Borrowed("th")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-thai", feature = "lang-th",))]
        ),
    },
    WordListDecl {
        name: "aosp_tagalog",
        ident: "AOSP_TAGALOG",
        rel_path: "aosp/tl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name : std::borrow::Cow::Borrowed("aosp_tagalog"),
            script : None, language : Some(std::borrow::Cow::Borrowed("tl")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "lang-tl",))]
        ),
    },
    WordListDecl {
        name: "aosp_turkish_latin",
        ident: "AOSP_TURKISH_LATIN",
        rel_path: "aosp/tr_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_turkish_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("tr")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-tr",))]
        ),
    },
    WordListDecl {
        name: "aosp_ukrainian_cyrillic",
        ident: "AOSP_UKRAINIAN_CYRILLIC",
        rel_path: "aosp/uk_Cyrl.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_ukrainian_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language :
            Some(std::borrow::Cow::Borrowed("uk")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-cyrl", feature = "lang-uk",))]
        ),
    },
    WordListDecl {
        name: "aosp_urdu_arabic",
        ident: "AOSP_URDU_ARABIC",
        rel_path: "aosp/ur_Arab.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_urdu_arabic"), script :
            Some(std::borrow::Cow::Borrowed("Arab")), language :
            Some(std::borrow::Cow::Borrowed("ur")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-arab", feature = "lang-ur",))]
        ),
    },
    WordListDecl {
        name: "aosp_uzbek_latin",
        ident: "AOSP_UZBEK_LATIN",
        rel_path: "aosp/uz_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_uzbek_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("uz")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-uz",))]
        ),
    },
    WordListDecl {
        name: "aosp_vietnamese_latin",
        ident: "AOSP_VIETNAMESE_LATIN",
        rel_path: "aosp/vi_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_vietnamese_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("vi")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-vi",))]
        ),
    },
    WordListDecl {
        name: "aosp_chinese_han",
        ident: "AOSP_CHINESE_HAN",
        rel_path: "aosp/zh_Hani.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_chinese_han"), script :
            Some(std::borrow::Cow::Borrowed("Hani")), language :
            Some(std::borrow::Cow::Borrowed("zh")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-hani", feature = "lang-zh",))]
        ),
    },
    WordListDecl {
        name: "aosp_zulu_latin",
        ident: "AOSP_ZULU_LATIN",
        rel_path: "aosp/zu_Latn.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("aosp_zulu_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language :
            Some(std::borrow::Cow::Borrowed("zu")), }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "aosp", feature = "script-latn", feature = "lang-zu",))]
        ),
    },
    WordListDecl {
        name: "diffenator_adlam",
        ident: "DIFFENATOR_ADLAM",
        rel_path: "diffenator/Adlam.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_adlam"), script :
            Some(std::borrow::Cow::Borrowed("Adlm")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-adlm",))]
        ),
    },
    WordListDecl {
        name: "diffenator_arabic",
        ident: "DIFFENATOR_ARABIC",
        rel_path: "diffenator/Arabic.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_arabic"), script :
            Some(std::borrow::Cow::Borrowed("Arab")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-arab",))]
        ),
    },
    WordListDecl {
        name: "diffenator_armenian",
        ident: "DIFFENATOR_ARMENIAN",
        rel_path: "diffenator/Armenian.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_armenian"), script :
            Some(std::borrow::Cow::Borrowed("Armn")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-armn",))]
        ),
    },
    WordListDecl {
        name: "diffenator_avestan",
        ident: "DIFFENATOR_AVESTAN",
        rel_path: "diffenator/Avestan.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_avestan"), script :
            Some(std::borrow::Cow::Borrowed("Avst")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-avst",))]
        ),
    },
    WordListDecl {
        name: "diffenator_bengali",
        ident: "DIFFENATOR_BENGALI",
        rel_path: "diffenator/Bengali.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_bengali"), script :
            Some(std::borrow::Cow::Borrowed("Beng")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-beng",))]
        ),
    },
    WordListDecl {
        name: "diffenator_bopomofo",
        ident: "DIFFENATOR_BOPOMOFO",
        rel_path: "diffenator/Bopomofo.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_bopomofo"), script :
            Some(std::borrow::Cow::Borrowed("Bopo")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-bopo",))]
        ),
    },
    WordListDecl {
        name: "diffenator_canadian_aboriginal",
        ident: "DIFFENATOR_CANADIAN_ABORIGINAL",
        rel_path: "diffenator/Canadian_Aboriginal.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_canadian_aboriginal"), script :
            Some(std::borrow::Cow::Borrowed("Cans")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-cans",))]
        ),
    },
    WordListDecl {
        name: "diffenator_chakma",
        ident: "DIFFENATOR_CHAKMA",
        rel_path: "diffenator/Chakma.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_chakma"), script :
            Some(std::borrow::Cow::Borrowed("Cakm")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-cakm",))]
        ),
    },
    WordListDecl {
        name: "diffenator_cherokee",
        ident: "DIFFENATOR_CHEROKEE",
        rel_path: "diffenator/Cherokee.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_cherokee"), script :
            Some(std::borrow::Cow::Borrowed("Cher")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-cher",))]
        ),
    },
    WordListDecl {
        name: "diffenator_common",
        ident: "DIFFENATOR_COMMON",
        rel_path: "diffenator/Common.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_common"), script :
            Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-zyyy",))]
        ),
    },
    WordListDecl {
        name: "diffenator_cyrillic",
        ident: "DIFFENATOR_CYRILLIC",
        rel_path: "diffenator/Cyrillic.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_cyrillic"), script :
            Some(std::borrow::Cow::Borrowed("Cyrl")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-cyrl",))]
        ),
    },
    WordListDecl {
        name: "diffenator_devanagari",
        ident: "DIFFENATOR_DEVANAGARI",
        rel_path: "diffenator/Devanagari.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_devanagari"), script :
            Some(std::borrow::Cow::Borrowed("Deva")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-deva",))]
        ),
    },
    WordListDecl {
        name: "diffenator_ethiopic",
        ident: "DIFFENATOR_ETHIOPIC",
        rel_path: "diffenator/Ethiopic.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_ethiopic"), script :
            Some(std::borrow::Cow::Borrowed("Ethi")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-ethi",))]
        ),
    },
    WordListDecl {
        name: "diffenator_georgian",
        ident: "DIFFENATOR_GEORGIAN",
        rel_path: "diffenator/Georgian.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_georgian"), script :
            Some(std::borrow::Cow::Borrowed("Geor")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-geor",))]
        ),
    },
    WordListDecl {
        name: "diffenator_greek",
        ident: "DIFFENATOR_GREEK",
        rel_path: "diffenator/Greek.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_greek"), script :
            Some(std::borrow::Cow::Borrowed("Grek")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-grek",))]
        ),
    },
    WordListDecl {
        name: "diffenator_gujarati",
        ident: "DIFFENATOR_GUJARATI",
        rel_path: "diffenator/Gujarati.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_gujarati"), script :
            Some(std::borrow::Cow::Borrowed("Gujr")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-gujr",))]
        ),
    },
    WordListDecl {
        name: "diffenator_gurmukhi",
        ident: "DIFFENATOR_GURMUKHI",
        rel_path: "diffenator/Gurmukhi.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_gurmukhi"), script :
            Some(std::borrow::Cow::Borrowed("Guru")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-guru",))]
        ),
    },
    WordListDecl {
        name: "diffenator_hebrew",
        ident: "DIFFENATOR_HEBREW",
        rel_path: "diffenator/Hebrew.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_hebrew"), script :
            Some(std::borrow::Cow::Borrowed("Hebr")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-hebr",))]
        ),
    },
    WordListDecl {
        name: "diffenator_hiragana",
        ident: "DIFFENATOR_HIRAGANA",
        rel_path: "diffenator/Hiragana.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_hiragana"), script :
            Some(std::borrow::Cow::Borrowed("Hira")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-hira",))]
        ),
    },
    WordListDecl {
        name: "diffenator_japanese",
        ident: "DIFFENATOR_JAPANESE",
        rel_path: "diffenator/Japanese.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_japanese"), script :
            Some(std::borrow::Cow::Borrowed("Jpan")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-jpan",))]
        ),
    },
    WordListDecl {
        name: "diffenator_katakana",
        ident: "DIFFENATOR_KATAKANA",
        rel_path: "diffenator/Katakana.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_katakana"), script :
            Some(std::borrow::Cow::Borrowed("Kana")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-kana",))]
        ),
    },
    WordListDecl {
        name: "diffenator_khmer",
        ident: "DIFFENATOR_KHMER",
        rel_path: "diffenator/Khmer.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_khmer"), script :
            Some(std::borrow::Cow::Borrowed("Khmr")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-khmr",))]
        ),
    },
    WordListDecl {
        name: "diffenator_lao",
        ident: "DIFFENATOR_LAO",
        rel_path: "diffenator/Lao.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_lao"), script :
            Some(std::borrow::Cow::Borrowed("Laoo")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-laoo",))]
        ),
    },
    WordListDecl {
        name: "diffenator_latin",
        ident: "DIFFENATOR_LATIN",
        rel_path: "diffenator/Latin.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_latin"), script :
            Some(std::borrow::Cow::Borrowed("Latn")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-latn",))]
        ),
    },
    WordListDecl {
        name: "diffenator_lisu",
        ident: "DIFFENATOR_LISU",
        rel_path: "diffenator/Lisu.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_lisu"), script :
            Some(std::borrow::Cow::Borrowed("Lisu")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-lisu",))]
        ),
    },
    WordListDecl {
        name: "diffenator_malayalam",
        ident: "DIFFENATOR_MALAYALAM",
        rel_path: "diffenator/Malayalam.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_malayalam"), script :
            Some(std::borrow::Cow::Borrowed("Mlym")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-mlym",))]
        ),
    },
    WordListDecl {
        name: "diffenator_mongolian",
        ident: "DIFFENATOR_MONGOLIAN",
        rel_path: "diffenator/Mongolian.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_mongolian"), script :
            Some(std::borrow::Cow::Borrowed("Mong")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-mong",))]
        ),
    },
    WordListDecl {
        name: "diffenator_myanmar",
        ident: "DIFFENATOR_MYANMAR",
        rel_path: "diffenator/Myanmar.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_myanmar"), script :
            Some(std::borrow::Cow::Borrowed("Mymr")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-mymr",))]
        ),
    },
    WordListDecl {
        name: "diffenator_ol_chiki",
        ident: "DIFFENATOR_OL_CHIKI",
        rel_path: "diffenator/Ol_Chiki.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_ol_chiki"), script :
            Some(std::borrow::Cow::Borrowed("Olck")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-olck",))]
        ),
    },
    WordListDecl {
        name: "diffenator_oriya",
        ident: "DIFFENATOR_ORIYA",
        rel_path: "diffenator/Oriya.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_oriya"), script :
            Some(std::borrow::Cow::Borrowed("Orya")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-orya",))]
        ),
    },
    WordListDecl {
        name: "diffenator_osage",
        ident: "DIFFENATOR_OSAGE",
        rel_path: "diffenator/Osage.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_osage"), script :
            Some(std::borrow::Cow::Borrowed("Osge")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-osge",))]
        ),
    },
    WordListDecl {
        name: "diffenator_sinhala",
        ident: "DIFFENATOR_SINHALA",
        rel_path: "diffenator/Sinhala.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_sinhala"), script :
            Some(std::borrow::Cow::Borrowed("Sinh")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-sinh",))]
        ),
    },
    WordListDecl {
        name: "diffenator_syriac",
        ident: "DIFFENATOR_SYRIAC",
        rel_path: "diffenator/Syriac.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_syriac"), script :
            Some(std::borrow::Cow::Borrowed("Syrc")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-syrc",))]
        ),
    },
    WordListDecl {
        name: "diffenator_tamil",
        ident: "DIFFENATOR_TAMIL",
        rel_path: "diffenator/Tamil.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_tamil"), script :
            Some(std::borrow::Cow::Borrowed("Taml")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-taml",))]
        ),
    },
    WordListDecl {
        name: "diffenator_telugu",
        ident: "DIFFENATOR_TELUGU",
        rel_path: "diffenator/Telugu.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_telugu"), script :
            Some(std::borrow::Cow::Borrowed("Telu")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-telu",))]
        ),
    },
    WordListDecl {
        name: "diffenator_thai",
        ident: "DIFFENATOR_THAI",
        rel_path: "diffenator/Thai.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_thai"), script :
            Some(std::borrow::Cow::Borrowed("Thai")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-thai",))]
        ),
    },
    WordListDecl {
        name: "diffenator_thanaa",
        ident: "DIFFENATOR_THANAA",
        rel_path: "diffenator/Thanaa.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_thanaa"), script :
            Some(std::borrow::Cow::Borrowed("Thaa")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-thaa",))]
        ),
    },
    WordListDecl {
        name: "diffenator_tibetan",
        ident: "DIFFENATOR_TIBETAN",
        rel_path: "diffenator/Tibetan.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_tibetan"), script :
            Some(std::borrow::Cow::Borrowed("Tibt")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-tibt",))]
        ),
    },
    WordListDecl {
        name: "diffenator_tifinagh",
        ident: "DIFFENATOR_TIFINAGH",
        rel_path: "diffenator/Tifinagh.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_tifinagh"), script :
            Some(std::borrow::Cow::Borrowed("Tfng")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-tfng",))]
        ),
    },
    WordListDecl {
        name: "diffenator_vai",
        ident: "DIFFENATOR_VAI",
        rel_path: "diffenator/Vai.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("diffenator_vai"), script :
            Some(std::borrow::Cow::Borrowed("Vaii")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "diffenator", feature = "script-vaii",))]
        ),
    },
    WordListDecl {
        name: "ucd_emoji_all",
        ident: "UCD_EMOJI_ALL",
        rel_path: "ucd/Emoji_All.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("ucd_emoji_all"), script :
            Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "ucd", feature = "script-zyyy",))]
        ),
    },
    WordListDecl {
        name: "ucd_emoji_color",
        ident: "UCD_EMOJI_COLOR",
        rel_path: "ucd/Emoji_Color.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("ucd_emoji_color"), script :
            Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "ucd", feature = "script-zyyy",))]
        ),
    },
    WordListDecl {
        name: "ucd_emoji_textual",
        ident: "UCD_EMOJI_TEXTUAL",
        rel_path: "ucd/Emoji_Textual.txt",
        metadata_decl: ::std::stringify!(
            crate ::WordListMetadata { name :
            std::borrow::Cow::Borrowed("ucd_emoji_textual"), script :
            Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }
        ),
        features_attr: ::std::stringify!(
            #[cfg(any(feature = "ucd", feature = "script-zyyy",))]
        ),
    },
];

