#!/usr/bin/env python3

"""
Generates Rust code to give struct names and file paths for the data/ directory,
which the build script won't necessarily have access to at compile time, as the
data/ directory isn't included in the publish crate.

Is this code to generate code to help generate code? Yes.
"""

from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
GENERATED_FILE = Path(__file__).parent / "chicken.rs"

RUST_TEMPLATE = """// @generated by egg.py
static WORD_LISTS: &[(Option<&str>, &str)] = &[
{tuples}
];
"""
LINE_TEMPLATE = '    ({metadata}, r"{path}"),'


def path_to_upper_camel_case(path: Path) -> str:
    return "".join(part.title() for part in path.with_suffix("").parts)


tuples = []
for text_file in DATA_DIR.rglob("*.txt"):
    text_file = text_file.relative_to(DATA_DIR)
    metadatafile = text_file.with_suffix(".json")
    if (DATA_DIR / metadatafile).exists():
        metadata = 'Some(r"' + str(metadatafile).replace("\\", "/") + '")'
    else:
        metadata = "None"
    line = LINE_TEMPLATE.format(
        metadata=metadata,
        path=str(text_file).replace("\\", "/"),
    )
    tuples.append(line)

GENERATED_FILE.write_text(RUST_TEMPLATE.format(tuples="\n".join(tuples)))
print("Wrote chicken.rs")
