#!/usr/bin/env python3

"""
Generates Rust code to give struct names and file paths for the data/ directory,
which the build script won't necessarily have access to at compile time, as the
data/ directory isn't included in the publish crate.

Is this code to generate code to help generate code? Yes.
"""

from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
GENERATED_FILE = Path(__file__).parent / "chicken.rs"

RUST_TEMPLATE = """// @generated by egg.py
static WORD_LISTS: &[(&str, &str)] = &[
{tuples}
];
"""
LINE_TEMPLATE = '    (r"{struct_name}", r"{path}"),'


def path_to_upper_camel_case(path: Path) -> str:
    return "".join(part.title() for part in path.with_suffix("").parts)


tuples = []
for text_file in DATA_DIR.rglob("*.txt"):
    text_file = text_file.relative_to(DATA_DIR)
    line = LINE_TEMPLATE.format(
        struct_name=path_to_upper_camel_case(text_file),
        path=str(text_file).replace("\\", "/"),
    )
    tuples.append(line)

GENERATED_FILE.write_text(RUST_TEMPLATE.format(tuples="\n".join(tuples)))
print("Wrote chicken.rs")
