#!/usr/bin/env python3

"""
Generates Rust code to give struct names and file paths for the data/ directory,
which the build script won't necessarily have access to at compile time, as the
data/ directory isn't included in the publish crate.

Is this code to generate code to help generate code? Yes.
"""

from pathlib import Path
import tomllib

DATA_DIR = Path(__file__).parent / "data"
GENERATED_FILE = Path(__file__).parent / "chicken.rs"

RUST_TEMPLATE = """// @generated by egg.py
static WORD_LISTS: &[(&str, Option<&str>, &str)] = &[
{tuples}
];
"""
LINE_TEMPLATE = '    (r"{name}", {metadata}, r"{path}"),'


def path_to_upper_camel_case(path: Path) -> str:
    return "".join(part.title() for part in path.with_suffix("").parts)


tuples = []
for text_file in sorted(DATA_DIR.rglob("*.txt")):
    text_file = text_file.relative_to(DATA_DIR)
    metadata_file = text_file.with_suffix(".toml")
    if (DATA_DIR / metadata_file).exists():
        metadata = 'Some(r"' + str(metadata_file).replace("\\", "/") + '")'
        name = tomllib.loads((DATA_DIR / metadata_file).read_text(encoding="utf-8"))["name"]
    else:
        metadata = "None"
        name = path_to_upper_camel_case(text_file)
    line = LINE_TEMPLATE.format(
        metadata=metadata,
        path=str(text_file).replace("\\", "/"),
        name=name,
    )
    tuples.append(line)

GENERATED_FILE.write_text(RUST_TEMPLATE.format(tuples="\n".join(tuples)))
print("Wrote chicken.rs")
