// @generated by cargo xtask slwl
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-af"))
)]
word_list! {
    ident : AOSP_AFRIKAANS_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_afrikaans_latin", Some("Latn"), Some("af")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/af_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-af")))]
///The
#[doc = ::std::stringify!(AOSP_AFRIKAANS_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_AFRIKAANS_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-ethi", feature = "lang-am"))
)]
word_list! {
    ident : AOSP_AMHARIC_ETHIOPIC, metadata : crate
    ::WordListMetadata::new("aosp_amharic_ethiopic", Some("Ethi"), Some("am")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/am_Ethi.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-ethi", feature = "lang-am")))]
///The
#[doc = ::std::stringify!(AOSP_AMHARIC_ETHIOPIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_AMHARIC_ETHIOPIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-arab", feature = "lang-ar"))
)]
word_list! {
    ident : AOSP_ARABIC, metadata : crate ::WordListMetadata::new("aosp_arabic",
    Some("Arab"), Some("ar")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ar_Arab.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-arab", feature = "lang-ar")))]
///The
#[doc = ::std::stringify!(AOSP_ARABIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ARABIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-beng", feature = "lang-as"))
)]
word_list! {
    ident : AOSP_ASSAMESE_BENGALI, metadata : crate
    ::WordListMetadata::new("aosp_assamese_bengali", Some("Beng"), Some("as")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/as_Beng.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-beng", feature = "lang-as")))]
///The
#[doc = ::std::stringify!(AOSP_ASSAMESE_BENGALI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ASSAMESE_BENGALI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-az"))
)]
word_list! {
    ident : AOSP_AZERBAIJANI_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_azerbaijani_latin", Some("Latn"), Some("az")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/az_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-az")))]
///The
#[doc = ::std::stringify!(AOSP_AZERBAIJANI_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_AZERBAIJANI_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-be"))
)]
word_list! {
    ident : AOSP_BELARUSIAN_CYRILLIC, metadata : crate
    ::WordListMetadata::new("aosp_belarusian_cyrillic", Some("Cyrl"), Some("be")), bytes
    : ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "aosp/be_Cyrl.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-be")))]
///The
#[doc = ::std::stringify!(AOSP_BELARUSIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BELARUSIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-be"))
)]
word_list! {
    ident : AOSP_BELARUSIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_belarusian_latin", Some("Latn"), Some("be")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/be_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-be")))]
///The
#[doc = ::std::stringify!(AOSP_BELARUSIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BELARUSIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-bg"))
)]
word_list! {
    ident : AOSP_BULGARIAN_CYRILLIC, metadata : crate
    ::WordListMetadata::new("aosp_bulgarian_cyrillic", Some("Cyrl"), Some("bg")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/bg_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-bg")))]
///The
#[doc = ::std::stringify!(AOSP_BULGARIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BULGARIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-beng", feature = "lang-bn"))
)]
word_list! {
    ident : AOSP_BENGALI, metadata : crate ::WordListMetadata::new("aosp_bengali",
    Some("Beng"), Some("bn")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/bn_Beng.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-beng", feature = "lang-bn")))]
///The
#[doc = ::std::stringify!(AOSP_BENGALI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BENGALI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-bs"))
)]
word_list! {
    ident : AOSP_BOSNIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_bosnian_latin", Some("Latn"), Some("bs")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/bs_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-bs")))]
///The
#[doc = ::std::stringify!(AOSP_BOSNIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BOSNIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-ca"))
)]
word_list! {
    ident : AOSP_CATALAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_catalan_latin", Some("Latn"), Some("ca")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ca_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-ca")))]
///The
#[doc = ::std::stringify!(AOSP_CATALAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CATALAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-cs"))
)]
word_list! {
    ident : AOSP_CZECH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_czech_latin", Some("Latn"), Some("cs")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/cs_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-cs")))]
///The
#[doc = ::std::stringify!(AOSP_CZECH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CZECH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-da"))
)]
word_list! {
    ident : AOSP_DANISH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_danish_latin", Some("Latn"), Some("da")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/da_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-da")))]
///The
#[doc = ::std::stringify!(AOSP_DANISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_DANISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-de"))
)]
word_list! {
    ident : AOSP_GERMAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_german_latin", Some("Latn"), Some("de")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/de_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-de")))]
///The
#[doc = ::std::stringify!(AOSP_GERMAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_GERMAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-grek", feature = "lang-el"))
)]
word_list! {
    ident : AOSP_MODERN_GREEK, metadata : crate
    ::WordListMetadata::new("aosp_modern_greek", Some("Grek"), Some("el")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/el_Grek.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-grek", feature = "lang-el")))]
///The
#[doc = ::std::stringify!(AOSP_MODERN_GREEK)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MODERN_GREEK: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-en"))
)]
word_list! {
    ident : AOSP_ENGLISH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_english_latin", Some("Latn"), Some("en")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/en_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-en")))]
///The
#[doc = ::std::stringify!(AOSP_ENGLISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ENGLISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-es"))
)]
word_list! {
    ident : AOSP_SPANISH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_spanish_latin", Some("Latn"), Some("es")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/es_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-es")))]
///The
#[doc = ::std::stringify!(AOSP_SPANISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SPANISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-et"))
)]
word_list! {
    ident : AOSP_ESTONIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_estonian_latin", Some("Latn"), Some("et")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/et_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-et")))]
///The
#[doc = ::std::stringify!(AOSP_ESTONIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ESTONIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-eu"))
)]
word_list! {
    ident : AOSP_BASQUE_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_basque_latin", Some("Latn"), Some("eu")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/eu_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-eu")))]
///The
#[doc = ::std::stringify!(AOSP_BASQUE_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BASQUE_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-arab", feature = "lang-fa"))
)]
word_list! {
    ident : AOSP_PERSIAN_ARABIC, metadata : crate
    ::WordListMetadata::new("aosp_persian_arabic", Some("Arab"), Some("fa")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/fa_Arab.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-arab", feature = "lang-fa")))]
///The
#[doc = ::std::stringify!(AOSP_PERSIAN_ARABIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_PERSIAN_ARABIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-fi"))
)]
word_list! {
    ident : AOSP_FINNISH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_finnish_latin", Some("Latn"), Some("fi")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/fi_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-fi")))]
///The
#[doc = ::std::stringify!(AOSP_FINNISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_FINNISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-fr"))
)]
word_list! {
    ident : AOSP_FRENCH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_french_latin", Some("Latn"), Some("fr")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/fr_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-fr")))]
///The
#[doc = ::std::stringify!(AOSP_FRENCH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_FRENCH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-gl"))
)]
word_list! {
    ident : AOSP_GALICIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_galician_latin", Some("Latn"), Some("gl")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/gl_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-gl")))]
///The
#[doc = ::std::stringify!(AOSP_GALICIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_GALICIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-gujr", feature = "lang-gu"))
)]
word_list! {
    ident : AOSP_GUJARATI, metadata : crate ::WordListMetadata::new("aosp_gujarati",
    Some("Gujr"), Some("gu")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/gu_Gujr.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-gujr", feature = "lang-gu")))]
///The
#[doc = ::std::stringify!(AOSP_GUJARATI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_GUJARATI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-deva", feature = "lang-hi"))
)]
word_list! {
    ident : AOSP_HINDI_DEVANAGARI, metadata : crate
    ::WordListMetadata::new("aosp_hindi_devanagari", Some("Deva"), Some("hi")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hi_Deva.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-deva", feature = "lang-hi")))]
///The
#[doc = ::std::stringify!(AOSP_HINDI_DEVANAGARI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_HINDI_DEVANAGARI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-hi"))
)]
word_list! {
    ident : AOSP_HINDI_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_hindi_latin", Some("Latn"), Some("hi")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hi_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-hi")))]
///The
#[doc = ::std::stringify!(AOSP_HINDI_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_HINDI_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-hr"))
)]
word_list! {
    ident : AOSP_CROATIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_croatian_latin", Some("Latn"), Some("hr")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hr_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-hr")))]
///The
#[doc = ::std::stringify!(AOSP_CROATIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CROATIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-hu"))
)]
word_list! {
    ident : AOSP_HUNGARIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_hungarian_latin", Some("Latn"), Some("hu")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hu_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-hu")))]
///The
#[doc = ::std::stringify!(AOSP_HUNGARIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_HUNGARIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-armn", feature = "lang-hy"))
)]
word_list! {
    ident : AOSP_ARMENIAN, metadata : crate ::WordListMetadata::new("aosp_armenian",
    Some("Armn"), Some("hy")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hy_Armn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-armn", feature = "lang-hy")))]
///The
#[doc = ::std::stringify!(AOSP_ARMENIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ARMENIAN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-is"))
)]
word_list! {
    ident : AOSP_ICELANDIC_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_icelandic_latin", Some("Latn"), Some("is")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/is_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-is")))]
///The
#[doc = ::std::stringify!(AOSP_ICELANDIC_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ICELANDIC_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-it"))
)]
word_list! {
    ident : AOSP_ITALIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_italian_latin", Some("Latn"), Some("it")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/it_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-it")))]
///The
#[doc = ::std::stringify!(AOSP_ITALIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ITALIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-hira", feature = "lang-ja"))
)]
word_list! {
    ident : AOSP_JAPANESE_HIRAGANA, metadata : crate
    ::WordListMetadata::new("aosp_japanese_hiragana", Some("Hira"), Some("ja")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ja_Hira.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-hira", feature = "lang-ja")))]
///The
#[doc = ::std::stringify!(AOSP_JAPANESE_HIRAGANA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_JAPANESE_HIRAGANA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-kana", feature = "lang-ja"))
)]
word_list! {
    ident : AOSP_JAPANESE_KATAKANA, metadata : crate
    ::WordListMetadata::new("aosp_japanese_katakana", Some("Kana"), Some("ja")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ja_Kana.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-kana", feature = "lang-ja")))]
///The
#[doc = ::std::stringify!(AOSP_JAPANESE_KATAKANA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_JAPANESE_KATAKANA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-geor", feature = "lang-ka"))
)]
word_list! {
    ident : AOSP_GEORGIAN, metadata : crate ::WordListMetadata::new("aosp_georgian",
    Some("Geor"), Some("ka")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ka_Geor.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-geor", feature = "lang-ka")))]
///The
#[doc = ::std::stringify!(AOSP_GEORGIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_GEORGIAN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-kk"))
)]
word_list! {
    ident : AOSP_KAZAKH_CYRILLIC, metadata : crate
    ::WordListMetadata::new("aosp_kazakh_cyrillic", Some("Cyrl"), Some("kk")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/kk_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-kk")))]
///The
#[doc = ::std::stringify!(AOSP_KAZAKH_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KAZAKH_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-kk"))
)]
word_list! {
    ident : AOSP_KAZAKH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_kazakh_latin", Some("Latn"), Some("kk")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/kk_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-kk")))]
///The
#[doc = ::std::stringify!(AOSP_KAZAKH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KAZAKH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-khmr", feature = "lang-km"))
)]
word_list! {
    ident : AOSP_CENTRAL_KHMER, metadata : crate
    ::WordListMetadata::new("aosp_central_khmer", Some("Khmr"), Some("km")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/km_Khmr.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-khmr", feature = "lang-km")))]
///The
#[doc = ::std::stringify!(AOSP_CENTRAL_KHMER)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CENTRAL_KHMER: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-knda", feature = "lang-kn"))
)]
word_list! {
    ident : AOSP_KANNADA, metadata : crate ::WordListMetadata::new("aosp_kannada",
    Some("Knda"), Some("kn")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/kn_Knda.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-knda", feature = "lang-kn")))]
///The
#[doc = ::std::stringify!(AOSP_KANNADA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KANNADA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-hang", feature = "lang-ko"))
)]
word_list! {
    ident : AOSP_KOREAN_HANGUL, metadata : crate
    ::WordListMetadata::new("aosp_korean_hangul", Some("Hang"), Some("ko")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ko_Hang.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-hang", feature = "lang-ko")))]
///The
#[doc = ::std::stringify!(AOSP_KOREAN_HANGUL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KOREAN_HANGUL: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-ky"))
)]
word_list! {
    ident : AOSP_KIRGHIZ_CYRILLIC, metadata : crate
    ::WordListMetadata::new("aosp_kirghiz_cyrillic", Some("Cyrl"), Some("ky")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ky_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-ky")))]
///The
#[doc = ::std::stringify!(AOSP_KIRGHIZ_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KIRGHIZ_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-ky"))
)]
word_list! {
    ident : AOSP_KIRGHIZ_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_kirghiz_latin", Some("Latn"), Some("ky")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ky_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-ky")))]
///The
#[doc = ::std::stringify!(AOSP_KIRGHIZ_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KIRGHIZ_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-laoo", feature = "lang-lo"))
)]
word_list! {
    ident : AOSP_LAO, metadata : crate ::WordListMetadata::new("aosp_lao", Some("Laoo"),
    Some("lo")), bytes : ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"),
    '/', "aosp/lo_Laoo.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-laoo", feature = "lang-lo")))]
///The
#[doc = ::std::stringify!(AOSP_LAO)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_LAO: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-lt"))
)]
word_list! {
    ident : AOSP_LITHUANIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_lithuanian_latin", Some("Latn"), Some("lt")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/lt_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-lt")))]
///The
#[doc = ::std::stringify!(AOSP_LITHUANIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_LITHUANIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-lv"))
)]
word_list! {
    ident : AOSP_LATVIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_latvian_latin", Some("Latn"), Some("lv")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/lv_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-lv")))]
///The
#[doc = ::std::stringify!(AOSP_LATVIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_LATVIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-mk"))
)]
word_list! {
    ident : AOSP_MACEDONIAN_CYRILLIC, metadata : crate
    ::WordListMetadata::new("aosp_macedonian_cyrillic", Some("Cyrl"), Some("mk")), bytes
    : ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "aosp/mk_Cyrl.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-mk")))]
///The
#[doc = ::std::stringify!(AOSP_MACEDONIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MACEDONIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-mlym", feature = "lang-ml"))
)]
word_list! {
    ident : AOSP_MALAYALAM, metadata : crate ::WordListMetadata::new("aosp_malayalam",
    Some("Mlym"), Some("ml")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ml_Mlym.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-mlym", feature = "lang-ml")))]
///The
#[doc = ::std::stringify!(AOSP_MALAYALAM)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MALAYALAM: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-mn"))
)]
word_list! {
    ident : AOSP_MONGOLIAN_CYRILLIC, metadata : crate
    ::WordListMetadata::new("aosp_mongolian_cyrillic", Some("Cyrl"), Some("mn")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/mn_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-mn")))]
///The
#[doc = ::std::stringify!(AOSP_MONGOLIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MONGOLIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-deva", feature = "lang-mr"))
)]
word_list! {
    ident : AOSP_MARATHI_DEVANAGARI, metadata : crate
    ::WordListMetadata::new("aosp_marathi_devanagari", Some("Deva"), Some("mr")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/mr_Deva.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-deva", feature = "lang-mr")))]
///The
#[doc = ::std::stringify!(AOSP_MARATHI_DEVANAGARI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MARATHI_DEVANAGARI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "aosp", feature = "lang-ms")))]
word_list! {
    ident : AOSP_MALAY, metadata : crate ::WordListMetadata::new("aosp_malay", None,
    Some("ms")), bytes : ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"),
    '/', "aosp/ms.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "lang-ms")))]
///The
#[doc = ::std::stringify!(AOSP_MALAY)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MALAY: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-mymr", feature = "lang-my"))
)]
word_list! {
    ident : AOSP_BURMESE_MYANMAR, metadata : crate
    ::WordListMetadata::new("aosp_burmese_myanmar", Some("Mymr"), Some("my")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/my_Mymr.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-mymr", feature = "lang-my")))]
///The
#[doc = ::std::stringify!(AOSP_BURMESE_MYANMAR)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BURMESE_MYANMAR: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-nb"))
)]
word_list! {
    ident : AOSP_NORWEGIAN_BOKMÅL_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_norwegian_bokmål_latin", Some("Latn"), Some("nb")),
    bytes : ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "aosp/nb_Latn.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-nb")))]
///The
#[doc = ::std::stringify!(AOSP_NORWEGIAN_BOKMÅL_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_NORWEGIAN_BOKMÅL_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-deva", feature = "lang-ne"))
)]
word_list! {
    ident : AOSP_NEPALI_DEVANAGARI, metadata : crate
    ::WordListMetadata::new("aosp_nepali_devanagari", Some("Deva"), Some("ne")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ne_Deva.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-deva", feature = "lang-ne")))]
///The
#[doc = ::std::stringify!(AOSP_NEPALI_DEVANAGARI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_NEPALI_DEVANAGARI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-nl"))
)]
word_list! {
    ident : AOSP_DUTCH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_dutch_latin", Some("Latn"), Some("nl")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/nl_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-nl")))]
///The
#[doc = ::std::stringify!(AOSP_DUTCH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_DUTCH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-orya", feature = "lang-or"))
)]
word_list! {
    ident : AOSP_ORIYA, metadata : crate ::WordListMetadata::new("aosp_oriya",
    Some("Orya"), Some("or")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/or_Orya.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-orya", feature = "lang-or")))]
///The
#[doc = ::std::stringify!(AOSP_ORIYA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ORIYA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-guru", feature = "lang-pa"))
)]
word_list! {
    ident : AOSP_PANJABI_GURMUKHI, metadata : crate
    ::WordListMetadata::new("aosp_panjabi_gurmukhi", Some("Guru"), Some("pa")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/pa_Guru.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-guru", feature = "lang-pa")))]
///The
#[doc = ::std::stringify!(AOSP_PANJABI_GURMUKHI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_PANJABI_GURMUKHI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-pl"))
)]
word_list! {
    ident : AOSP_POLISH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_polish_latin", Some("Latn"), Some("pl")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/pl_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-pl")))]
///The
#[doc = ::std::stringify!(AOSP_POLISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_POLISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-pt"))
)]
word_list! {
    ident : AOSP_PORTUGUESE_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_portuguese_latin", Some("Latn"), Some("pt")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/pt_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-pt")))]
///The
#[doc = ::std::stringify!(AOSP_PORTUGUESE_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_PORTUGUESE_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-rm"))
)]
word_list! {
    ident : AOSP_ROMANSH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_romansh_latin", Some("Latn"), Some("rm")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/rm_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-rm")))]
///The
#[doc = ::std::stringify!(AOSP_ROMANSH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ROMANSH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-ro"))
)]
word_list! {
    ident : AOSP_ROMANIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_romanian_latin", Some("Latn"), Some("ro")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ro_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-ro")))]
///The
#[doc = ::std::stringify!(AOSP_ROMANIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ROMANIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-ru"))
)]
word_list! {
    ident : AOSP_RUSSIAN_CYRILLIC, metadata : crate
    ::WordListMetadata::new("aosp_russian_cyrillic", Some("Cyrl"), Some("ru")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ru_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-ru")))]
///The
#[doc = ::std::stringify!(AOSP_RUSSIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_RUSSIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-sinh", feature = "lang-si"))
)]
word_list! {
    ident : AOSP_SINHALA, metadata : crate ::WordListMetadata::new("aosp_sinhala",
    Some("Sinh"), Some("si")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/si_Sinh.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-sinh", feature = "lang-si")))]
///The
#[doc = ::std::stringify!(AOSP_SINHALA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SINHALA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sk"))
)]
word_list! {
    ident : AOSP_SLOVAK_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_slovak_latin", Some("Latn"), Some("sk")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sk_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sk")))]
///The
#[doc = ::std::stringify!(AOSP_SLOVAK_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SLOVAK_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sl"))
)]
word_list! {
    ident : AOSP_SLOVENIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_slovenian_latin", Some("Latn"), Some("sl")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sl_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sl")))]
///The
#[doc = ::std::stringify!(AOSP_SLOVENIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SLOVENIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sq"))
)]
word_list! {
    ident : AOSP_ALBANIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_albanian_latin", Some("Latn"), Some("sq")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sq_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sq")))]
///The
#[doc = ::std::stringify!(AOSP_ALBANIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ALBANIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-sr"))
)]
word_list! {
    ident : AOSP_SERBIAN_CYRILLIC, metadata : crate
    ::WordListMetadata::new("aosp_serbian_cyrillic", Some("Cyrl"), Some("sr")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sr_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-sr")))]
///The
#[doc = ::std::stringify!(AOSP_SERBIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SERBIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sr"))
)]
word_list! {
    ident : AOSP_SERBIAN_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_serbian_latin", Some("Latn"), Some("sr")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sr_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sr")))]
///The
#[doc = ::std::stringify!(AOSP_SERBIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SERBIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sv"))
)]
word_list! {
    ident : AOSP_SWEDISH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_swedish_latin", Some("Latn"), Some("sv")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sv_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sv")))]
///The
#[doc = ::std::stringify!(AOSP_SWEDISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SWEDISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sw"))
)]
word_list! {
    ident : AOSP_SWAHILI_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_swahili_latin", Some("Latn"), Some("sw")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sw_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sw")))]
///The
#[doc = ::std::stringify!(AOSP_SWAHILI_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SWAHILI_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-taml", feature = "lang-ta"))
)]
word_list! {
    ident : AOSP_TAMIL, metadata : crate ::WordListMetadata::new("aosp_tamil",
    Some("Taml"), Some("ta")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ta_Taml.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-taml", feature = "lang-ta")))]
///The
#[doc = ::std::stringify!(AOSP_TAMIL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_TAMIL: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-telu", feature = "lang-te"))
)]
word_list! {
    ident : AOSP_TELUGU, metadata : crate ::WordListMetadata::new("aosp_telugu",
    Some("Telu"), Some("te")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/te_Telu.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-telu", feature = "lang-te")))]
///The
#[doc = ::std::stringify!(AOSP_TELUGU)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_TELUGU: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-thai", feature = "lang-th"))
)]
word_list! {
    ident : AOSP_THAI, metadata : crate ::WordListMetadata::new("aosp_thai",
    Some("Thai"), Some("th")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/th_Thai.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-thai", feature = "lang-th")))]
///The
#[doc = ::std::stringify!(AOSP_THAI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_THAI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "aosp", feature = "lang-tl")))]
word_list! {
    ident : AOSP_TAGALOG, metadata : crate ::WordListMetadata::new("aosp_tagalog", None,
    Some("tl")), bytes : ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"),
    '/', "aosp/tl.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "lang-tl")))]
///The
#[doc = ::std::stringify!(AOSP_TAGALOG)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_TAGALOG: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-tr"))
)]
word_list! {
    ident : AOSP_TURKISH_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_turkish_latin", Some("Latn"), Some("tr")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/tr_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-tr")))]
///The
#[doc = ::std::stringify!(AOSP_TURKISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_TURKISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-uk"))
)]
word_list! {
    ident : AOSP_UKRAINIAN_CYRILLIC, metadata : crate
    ::WordListMetadata::new("aosp_ukrainian_cyrillic", Some("Cyrl"), Some("uk")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/uk_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-uk")))]
///The
#[doc = ::std::stringify!(AOSP_UKRAINIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_UKRAINIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-arab", feature = "lang-ur"))
)]
word_list! {
    ident : AOSP_URDU_ARABIC, metadata : crate
    ::WordListMetadata::new("aosp_urdu_arabic", Some("Arab"), Some("ur")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ur_Arab.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-arab", feature = "lang-ur")))]
///The
#[doc = ::std::stringify!(AOSP_URDU_ARABIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_URDU_ARABIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-uz"))
)]
word_list! {
    ident : AOSP_UZBEK_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_uzbek_latin", Some("Latn"), Some("uz")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/uz_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-uz")))]
///The
#[doc = ::std::stringify!(AOSP_UZBEK_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_UZBEK_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-vi"))
)]
word_list! {
    ident : AOSP_VIETNAMESE_LATIN, metadata : crate
    ::WordListMetadata::new("aosp_vietnamese_latin", Some("Latn"), Some("vi")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/vi_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-vi")))]
///The
#[doc = ::std::stringify!(AOSP_VIETNAMESE_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_VIETNAMESE_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-hani", feature = "lang-zh"))
)]
word_list! {
    ident : AOSP_CHINESE_HAN, metadata : crate
    ::WordListMetadata::new("aosp_chinese_han", Some("Hani"), Some("zh")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/zh_Hani.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-hani", feature = "lang-zh")))]
///The
#[doc = ::std::stringify!(AOSP_CHINESE_HAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CHINESE_HAN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-zu"))
)]
word_list! {
    ident : AOSP_ZULU_LATIN, metadata : crate ::WordListMetadata::new("aosp_zulu_latin",
    Some("Latn"), Some("zu")), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/zu_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-zu")))]
///The
#[doc = ::std::stringify!(AOSP_ZULU_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ZULU_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-adlm")))]
word_list! {
    ident : DIFFENATOR_ADLAM, metadata : crate
    ::WordListMetadata::new("diffenator_adlam", Some("Adlm"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Adlam.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-adlm")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ADLAM)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ADLAM: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-arab")))]
word_list! {
    ident : DIFFENATOR_ARABIC, metadata : crate
    ::WordListMetadata::new("diffenator_arabic", Some("Arab"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Arabic.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-arab")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ARABIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ARABIC: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-armn")))]
word_list! {
    ident : DIFFENATOR_ARMENIAN, metadata : crate
    ::WordListMetadata::new("diffenator_armenian", Some("Armn"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Armenian.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-armn")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ARMENIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ARMENIAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-avst")))]
word_list! {
    ident : DIFFENATOR_AVESTAN, metadata : crate
    ::WordListMetadata::new("diffenator_avestan", Some("Avst"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Avestan.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-avst")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_AVESTAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_AVESTAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-beng")))]
word_list! {
    ident : DIFFENATOR_BENGALI, metadata : crate
    ::WordListMetadata::new("diffenator_bengali", Some("Beng"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Bengali.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-beng")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_BENGALI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_BENGALI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-bopo")))]
word_list! {
    ident : DIFFENATOR_BOPOMOFO, metadata : crate
    ::WordListMetadata::new("diffenator_bopomofo", Some("Bopo"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Bopomofo.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-bopo")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_BOPOMOFO)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_BOPOMOFO: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-cans")))]
word_list! {
    ident : DIFFENATOR_CANADIAN_ABORIGINAL, metadata : crate
    ::WordListMetadata::new("diffenator_canadian_aboriginal", Some("Cans"), None), bytes
    : ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Canadian_Aboriginal.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-cans")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_CANADIAN_ABORIGINAL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_CANADIAN_ABORIGINAL: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-cakm")))]
word_list! {
    ident : DIFFENATOR_CHAKMA, metadata : crate
    ::WordListMetadata::new("diffenator_chakma", Some("Cakm"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Chakma.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-cakm")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_CHAKMA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_CHAKMA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-cher")))]
word_list! {
    ident : DIFFENATOR_CHEROKEE, metadata : crate
    ::WordListMetadata::new("diffenator_cherokee", Some("Cher"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Cherokee.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-cher")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_CHEROKEE)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_CHEROKEE: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-zyyy")))]
word_list! {
    ident : DIFFENATOR_COMMON, metadata : crate
    ::WordListMetadata::new("diffenator_common", Some("Zyyy"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Common.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-zyyy")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_COMMON)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_COMMON: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-cyrl")))]
word_list! {
    ident : DIFFENATOR_CYRILLIC, metadata : crate
    ::WordListMetadata::new("diffenator_cyrillic", Some("Cyrl"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Cyrillic.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-cyrl")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-deva")))]
word_list! {
    ident : DIFFENATOR_DEVANAGARI, metadata : crate
    ::WordListMetadata::new("diffenator_devanagari", Some("Deva"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Devanagari.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-deva")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_DEVANAGARI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_DEVANAGARI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-ethi")))]
word_list! {
    ident : DIFFENATOR_ETHIOPIC, metadata : crate
    ::WordListMetadata::new("diffenator_ethiopic", Some("Ethi"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Ethiopic.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-ethi")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ETHIOPIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ETHIOPIC: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-geor")))]
word_list! {
    ident : DIFFENATOR_GEORGIAN, metadata : crate
    ::WordListMetadata::new("diffenator_georgian", Some("Geor"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Georgian.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-geor")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_GEORGIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_GEORGIAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-grek")))]
word_list! {
    ident : DIFFENATOR_GREEK, metadata : crate
    ::WordListMetadata::new("diffenator_greek", Some("Grek"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Greek.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-grek")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_GREEK)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_GREEK: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-gujr")))]
word_list! {
    ident : DIFFENATOR_GUJARATI, metadata : crate
    ::WordListMetadata::new("diffenator_gujarati", Some("Gujr"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Gujarati.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-gujr")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_GUJARATI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_GUJARATI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-guru")))]
word_list! {
    ident : DIFFENATOR_GURMUKHI, metadata : crate
    ::WordListMetadata::new("diffenator_gurmukhi", Some("Guru"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Gurmukhi.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-guru")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_GURMUKHI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_GURMUKHI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-hebr")))]
word_list! {
    ident : DIFFENATOR_HEBREW, metadata : crate
    ::WordListMetadata::new("diffenator_hebrew", Some("Hebr"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Hebrew.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-hebr")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_HEBREW)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_HEBREW: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-hira")))]
word_list! {
    ident : DIFFENATOR_HIRAGANA, metadata : crate
    ::WordListMetadata::new("diffenator_hiragana", Some("Hira"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Hiragana.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-hira")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_HIRAGANA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_HIRAGANA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-jpan")))]
word_list! {
    ident : DIFFENATOR_JAPANESE, metadata : crate
    ::WordListMetadata::new("diffenator_japanese", Some("Jpan"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Japanese.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-jpan")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_JAPANESE)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_JAPANESE: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-kana")))]
word_list! {
    ident : DIFFENATOR_KATAKANA, metadata : crate
    ::WordListMetadata::new("diffenator_katakana", Some("Kana"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Katakana.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-kana")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_KATAKANA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_KATAKANA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-khmr")))]
word_list! {
    ident : DIFFENATOR_KHMER, metadata : crate
    ::WordListMetadata::new("diffenator_khmer", Some("Khmr"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Khmer.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-khmr")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_KHMER)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_KHMER: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-laoo")))]
word_list! {
    ident : DIFFENATOR_LAO, metadata : crate ::WordListMetadata::new("diffenator_lao",
    Some("Laoo"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Lao.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-laoo")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_LAO)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_LAO: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-latn")))]
word_list! {
    ident : DIFFENATOR_LATIN, metadata : crate
    ::WordListMetadata::new("diffenator_latin", Some("Latn"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Latin.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-latn")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-lisu")))]
word_list! {
    ident : DIFFENATOR_LISU, metadata : crate ::WordListMetadata::new("diffenator_lisu",
    Some("Lisu"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Lisu.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-lisu")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_LISU)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_LISU: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-mlym")))]
word_list! {
    ident : DIFFENATOR_MALAYALAM, metadata : crate
    ::WordListMetadata::new("diffenator_malayalam", Some("Mlym"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Malayalam.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-mlym")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_MALAYALAM)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_MALAYALAM: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-mong")))]
word_list! {
    ident : DIFFENATOR_MONGOLIAN, metadata : crate
    ::WordListMetadata::new("diffenator_mongolian", Some("Mong"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Mongolian.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-mong")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_MONGOLIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_MONGOLIAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-mymr")))]
word_list! {
    ident : DIFFENATOR_MYANMAR, metadata : crate
    ::WordListMetadata::new("diffenator_myanmar", Some("Mymr"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Myanmar.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-mymr")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_MYANMAR)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_MYANMAR: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-olck")))]
word_list! {
    ident : DIFFENATOR_OL_CHIKI, metadata : crate
    ::WordListMetadata::new("diffenator_ol_chiki", Some("Olck"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Ol_Chiki.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-olck")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_OL_CHIKI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_OL_CHIKI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-orya")))]
word_list! {
    ident : DIFFENATOR_ORIYA, metadata : crate
    ::WordListMetadata::new("diffenator_oriya", Some("Orya"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Oriya.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-orya")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ORIYA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ORIYA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-osge")))]
word_list! {
    ident : DIFFENATOR_OSAGE, metadata : crate
    ::WordListMetadata::new("diffenator_osage", Some("Osge"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Osage.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-osge")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_OSAGE)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_OSAGE: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-sinh")))]
word_list! {
    ident : DIFFENATOR_SINHALA, metadata : crate
    ::WordListMetadata::new("diffenator_sinhala", Some("Sinh"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Sinhala.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-sinh")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_SINHALA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_SINHALA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-syrc")))]
word_list! {
    ident : DIFFENATOR_SYRIAC, metadata : crate
    ::WordListMetadata::new("diffenator_syriac", Some("Syrc"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Syriac.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-syrc")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_SYRIAC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_SYRIAC: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-taml")))]
word_list! {
    ident : DIFFENATOR_TAMIL, metadata : crate
    ::WordListMetadata::new("diffenator_tamil", Some("Taml"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Tamil.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-taml")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_TAMIL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_TAMIL: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-telu")))]
word_list! {
    ident : DIFFENATOR_TELUGU, metadata : crate
    ::WordListMetadata::new("diffenator_telugu", Some("Telu"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Telugu.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-telu")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_TELUGU)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_TELUGU: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-thai")))]
word_list! {
    ident : DIFFENATOR_THAI, metadata : crate ::WordListMetadata::new("diffenator_thai",
    Some("Thai"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Thai.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-thai")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_THAI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_THAI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-thaa")))]
word_list! {
    ident : DIFFENATOR_THANAA, metadata : crate
    ::WordListMetadata::new("diffenator_thanaa", Some("Thaa"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Thanaa.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-thaa")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_THANAA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_THANAA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-tibt")))]
word_list! {
    ident : DIFFENATOR_TIBETAN, metadata : crate
    ::WordListMetadata::new("diffenator_tibetan", Some("Tibt"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Tibetan.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-tibt")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_TIBETAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_TIBETAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-tfng")))]
word_list! {
    ident : DIFFENATOR_TIFINAGH, metadata : crate
    ::WordListMetadata::new("diffenator_tifinagh", Some("Tfng"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Tifinagh.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-tfng")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_TIFINAGH)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_TIFINAGH: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-vaii")))]
word_list! {
    ident : DIFFENATOR_VAI, metadata : crate ::WordListMetadata::new("diffenator_vai",
    Some("Vaii"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Vai.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-vaii")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_VAI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_VAI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "ucd", feature = "script-zyyy")))]
word_list! {
    ident : UCD_EMOJI_ALL, metadata : crate ::WordListMetadata::new("ucd_emoji_all",
    Some("Zyyy"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "ucd/Emoji_All.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "ucd", feature = "script-zyyy")))]
///The
#[doc = ::std::stringify!(UCD_EMOJI_ALL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static UCD_EMOJI_ALL: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "ucd", feature = "script-zyyy")))]
word_list! {
    ident : UCD_EMOJI_COLOR, metadata : crate ::WordListMetadata::new("ucd_emoji_color",
    Some("Zyyy"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "ucd/Emoji_Color.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "ucd", feature = "script-zyyy")))]
///The
#[doc = ::std::stringify!(UCD_EMOJI_COLOR)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static UCD_EMOJI_COLOR: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "ucd", feature = "script-zyyy")))]
word_list! {
    ident : UCD_EMOJI_TEXTUAL, metadata : crate
    ::WordListMetadata::new("ucd_emoji_textual", Some("Zyyy"), None), bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "ucd/Emoji_Textual.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "ucd", feature = "script-zyyy")))]
///The
#[doc = ::std::stringify!(UCD_EMOJI_TEXTUAL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static UCD_EMOJI_TEXTUAL: crate::WordList = crate::WordList::stub();
