// @generated by cargo xtask slwl
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-af"))
)]
wordlist! {
    ident : AOSP_AFRIKAANS_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_afrikaans_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("af")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/af_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-af")))]
///The
#[doc = ::std::stringify!(AOSP_AFRIKAANS_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_AFRIKAANS_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-ethi", feature = "lang-am"))
)]
wordlist! {
    ident : AOSP_AMHARIC_ETHIOPIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_amharic_ethiopic"), script :
    Some(std::borrow::Cow::Borrowed("Ethi")), language :
    Some(std::borrow::Cow::Borrowed("am")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/am_Ethi.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-ethi", feature = "lang-am")))]
///The
#[doc = ::std::stringify!(AOSP_AMHARIC_ETHIOPIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_AMHARIC_ETHIOPIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-arab", feature = "lang-ar"))
)]
wordlist! {
    ident : AOSP_ARABIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_arabic"), script :
    Some(std::borrow::Cow::Borrowed("Arab")), language :
    Some(std::borrow::Cow::Borrowed("ar")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ar_Arab.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-arab", feature = "lang-ar")))]
///The
#[doc = ::std::stringify!(AOSP_ARABIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ARABIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-beng", feature = "lang-as"))
)]
wordlist! {
    ident : AOSP_ASSAMESE_BENGALI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_assamese_bengali"), script :
    Some(std::borrow::Cow::Borrowed("Beng")), language :
    Some(std::borrow::Cow::Borrowed("as")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/as_Beng.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-beng", feature = "lang-as")))]
///The
#[doc = ::std::stringify!(AOSP_ASSAMESE_BENGALI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ASSAMESE_BENGALI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-az"))
)]
wordlist! {
    ident : AOSP_AZERBAIJANI_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_azerbaijani_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("az")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/az_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-az")))]
///The
#[doc = ::std::stringify!(AOSP_AZERBAIJANI_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_AZERBAIJANI_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-be"))
)]
wordlist! {
    ident : AOSP_BELARUSIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_belarusian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("be")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/be_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-be")))]
///The
#[doc = ::std::stringify!(AOSP_BELARUSIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BELARUSIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-be"))
)]
wordlist! {
    ident : AOSP_BELARUSIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_belarusian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("be")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/be_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-be")))]
///The
#[doc = ::std::stringify!(AOSP_BELARUSIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BELARUSIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-bg"))
)]
wordlist! {
    ident : AOSP_BULGARIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_bulgarian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("bg")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/bg_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-bg")))]
///The
#[doc = ::std::stringify!(AOSP_BULGARIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BULGARIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-beng", feature = "lang-bn"))
)]
wordlist! {
    ident : AOSP_BENGALI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_bengali"), script :
    Some(std::borrow::Cow::Borrowed("Beng")), language :
    Some(std::borrow::Cow::Borrowed("bn")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/bn_Beng.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-beng", feature = "lang-bn")))]
///The
#[doc = ::std::stringify!(AOSP_BENGALI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BENGALI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-bs"))
)]
wordlist! {
    ident : AOSP_BOSNIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_bosnian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("bs")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/bs_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-bs")))]
///The
#[doc = ::std::stringify!(AOSP_BOSNIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BOSNIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-ca"))
)]
wordlist! {
    ident : AOSP_CATALAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_catalan_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("ca")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ca_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-ca")))]
///The
#[doc = ::std::stringify!(AOSP_CATALAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CATALAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-cs"))
)]
wordlist! {
    ident : AOSP_CZECH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_czech_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("cs")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/cs_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-cs")))]
///The
#[doc = ::std::stringify!(AOSP_CZECH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CZECH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-da"))
)]
wordlist! {
    ident : AOSP_DANISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_danish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("da")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/da_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-da")))]
///The
#[doc = ::std::stringify!(AOSP_DANISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_DANISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-de"))
)]
wordlist! {
    ident : AOSP_GERMAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_german_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("de")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/de_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-de")))]
///The
#[doc = ::std::stringify!(AOSP_GERMAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_GERMAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-grek", feature = "lang-el"))
)]
wordlist! {
    ident : AOSP_MODERN_GREEK, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_modern_greek"), script :
    Some(std::borrow::Cow::Borrowed("Grek")), language :
    Some(std::borrow::Cow::Borrowed("el")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/el_Grek.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-grek", feature = "lang-el")))]
///The
#[doc = ::std::stringify!(AOSP_MODERN_GREEK)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MODERN_GREEK: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-en"))
)]
wordlist! {
    ident : AOSP_ENGLISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_english_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("en")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/en_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-en")))]
///The
#[doc = ::std::stringify!(AOSP_ENGLISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ENGLISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-es"))
)]
wordlist! {
    ident : AOSP_SPANISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_spanish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("es")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/es_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-es")))]
///The
#[doc = ::std::stringify!(AOSP_SPANISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SPANISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-et"))
)]
wordlist! {
    ident : AOSP_ESTONIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_estonian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("et")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/et_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-et")))]
///The
#[doc = ::std::stringify!(AOSP_ESTONIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ESTONIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-eu"))
)]
wordlist! {
    ident : AOSP_BASQUE_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_basque_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("eu")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/eu_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-eu")))]
///The
#[doc = ::std::stringify!(AOSP_BASQUE_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BASQUE_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-arab", feature = "lang-fa"))
)]
wordlist! {
    ident : AOSP_PERSIAN_ARABIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_persian_arabic"), script :
    Some(std::borrow::Cow::Borrowed("Arab")), language :
    Some(std::borrow::Cow::Borrowed("fa")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/fa_Arab.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-arab", feature = "lang-fa")))]
///The
#[doc = ::std::stringify!(AOSP_PERSIAN_ARABIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_PERSIAN_ARABIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-fi"))
)]
wordlist! {
    ident : AOSP_FINNISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_finnish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("fi")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/fi_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-fi")))]
///The
#[doc = ::std::stringify!(AOSP_FINNISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_FINNISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-fr"))
)]
wordlist! {
    ident : AOSP_FRENCH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_french_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("fr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/fr_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-fr")))]
///The
#[doc = ::std::stringify!(AOSP_FRENCH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_FRENCH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-gl"))
)]
wordlist! {
    ident : AOSP_GALICIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_galician_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("gl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/gl_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-gl")))]
///The
#[doc = ::std::stringify!(AOSP_GALICIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_GALICIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-gujr", feature = "lang-gu"))
)]
wordlist! {
    ident : AOSP_GUJARATI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_gujarati"), script :
    Some(std::borrow::Cow::Borrowed("Gujr")), language :
    Some(std::borrow::Cow::Borrowed("gu")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/gu_Gujr.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-gujr", feature = "lang-gu")))]
///The
#[doc = ::std::stringify!(AOSP_GUJARATI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_GUJARATI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-deva", feature = "lang-hi"))
)]
wordlist! {
    ident : AOSP_HINDI_DEVANAGARI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_hindi_devanagari"), script :
    Some(std::borrow::Cow::Borrowed("Deva")), language :
    Some(std::borrow::Cow::Borrowed("hi")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hi_Deva.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-deva", feature = "lang-hi")))]
///The
#[doc = ::std::stringify!(AOSP_HINDI_DEVANAGARI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_HINDI_DEVANAGARI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-hi"))
)]
wordlist! {
    ident : AOSP_HINDI_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_hindi_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("hi")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hi_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-hi")))]
///The
#[doc = ::std::stringify!(AOSP_HINDI_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_HINDI_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-hr"))
)]
wordlist! {
    ident : AOSP_CROATIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_croatian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("hr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hr_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-hr")))]
///The
#[doc = ::std::stringify!(AOSP_CROATIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CROATIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-hu"))
)]
wordlist! {
    ident : AOSP_HUNGARIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_hungarian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("hu")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hu_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-hu")))]
///The
#[doc = ::std::stringify!(AOSP_HUNGARIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_HUNGARIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-armn", feature = "lang-hy"))
)]
wordlist! {
    ident : AOSP_ARMENIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_armenian"), script :
    Some(std::borrow::Cow::Borrowed("Armn")), language :
    Some(std::borrow::Cow::Borrowed("hy")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hy_Armn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-armn", feature = "lang-hy")))]
///The
#[doc = ::std::stringify!(AOSP_ARMENIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ARMENIAN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-is"))
)]
wordlist! {
    ident : AOSP_ICELANDIC_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_icelandic_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("is")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/is_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-is")))]
///The
#[doc = ::std::stringify!(AOSP_ICELANDIC_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ICELANDIC_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-it"))
)]
wordlist! {
    ident : AOSP_ITALIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_italian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("it")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/it_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-it")))]
///The
#[doc = ::std::stringify!(AOSP_ITALIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ITALIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-hira", feature = "lang-ja"))
)]
wordlist! {
    ident : AOSP_JAPANESE_HIRAGANA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_japanese_hiragana"), script :
    Some(std::borrow::Cow::Borrowed("Hira")), language :
    Some(std::borrow::Cow::Borrowed("ja")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ja_Hira.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-hira", feature = "lang-ja")))]
///The
#[doc = ::std::stringify!(AOSP_JAPANESE_HIRAGANA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_JAPANESE_HIRAGANA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-kana", feature = "lang-ja"))
)]
wordlist! {
    ident : AOSP_JAPANESE_KATAKANA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_japanese_katakana"), script :
    Some(std::borrow::Cow::Borrowed("Kana")), language :
    Some(std::borrow::Cow::Borrowed("ja")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ja_Kana.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-kana", feature = "lang-ja")))]
///The
#[doc = ::std::stringify!(AOSP_JAPANESE_KATAKANA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_JAPANESE_KATAKANA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-geor", feature = "lang-ka"))
)]
wordlist! {
    ident : AOSP_GEORGIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_georgian"), script :
    Some(std::borrow::Cow::Borrowed("Geor")), language :
    Some(std::borrow::Cow::Borrowed("ka")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ka_Geor.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-geor", feature = "lang-ka")))]
///The
#[doc = ::std::stringify!(AOSP_GEORGIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_GEORGIAN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-kk"))
)]
wordlist! {
    ident : AOSP_KAZAKH_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kazakh_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("kk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/kk_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-kk")))]
///The
#[doc = ::std::stringify!(AOSP_KAZAKH_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KAZAKH_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-kk"))
)]
wordlist! {
    ident : AOSP_KAZAKH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kazakh_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("kk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/kk_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-kk")))]
///The
#[doc = ::std::stringify!(AOSP_KAZAKH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KAZAKH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-khmr", feature = "lang-km"))
)]
wordlist! {
    ident : AOSP_CENTRAL_KHMER, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_central_khmer"), script :
    Some(std::borrow::Cow::Borrowed("Khmr")), language :
    Some(std::borrow::Cow::Borrowed("km")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/km_Khmr.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-khmr", feature = "lang-km")))]
///The
#[doc = ::std::stringify!(AOSP_CENTRAL_KHMER)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CENTRAL_KHMER: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-knda", feature = "lang-kn"))
)]
wordlist! {
    ident : AOSP_KANNADA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kannada"), script :
    Some(std::borrow::Cow::Borrowed("Knda")), language :
    Some(std::borrow::Cow::Borrowed("kn")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/kn_Knda.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-knda", feature = "lang-kn")))]
///The
#[doc = ::std::stringify!(AOSP_KANNADA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KANNADA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-hang", feature = "lang-ko"))
)]
wordlist! {
    ident : AOSP_KOREAN_HANGUL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_korean_hangul"), script :
    Some(std::borrow::Cow::Borrowed("Hang")), language :
    Some(std::borrow::Cow::Borrowed("ko")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ko_Hang.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-hang", feature = "lang-ko")))]
///The
#[doc = ::std::stringify!(AOSP_KOREAN_HANGUL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KOREAN_HANGUL: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-ky"))
)]
wordlist! {
    ident : AOSP_KIRGHIZ_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kirghiz_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("ky")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ky_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-ky")))]
///The
#[doc = ::std::stringify!(AOSP_KIRGHIZ_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KIRGHIZ_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-ky"))
)]
wordlist! {
    ident : AOSP_KIRGHIZ_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kirghiz_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("ky")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ky_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-ky")))]
///The
#[doc = ::std::stringify!(AOSP_KIRGHIZ_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_KIRGHIZ_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-laoo", feature = "lang-lo"))
)]
wordlist! {
    ident : AOSP_LAO, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_lao"), script :
    Some(std::borrow::Cow::Borrowed("Laoo")), language :
    Some(std::borrow::Cow::Borrowed("lo")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/lo_Laoo.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-laoo", feature = "lang-lo")))]
///The
#[doc = ::std::stringify!(AOSP_LAO)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_LAO: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-lt"))
)]
wordlist! {
    ident : AOSP_LITHUANIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_lithuanian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("lt")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/lt_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-lt")))]
///The
#[doc = ::std::stringify!(AOSP_LITHUANIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_LITHUANIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-lv"))
)]
wordlist! {
    ident : AOSP_LATVIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_latvian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("lv")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/lv_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-lv")))]
///The
#[doc = ::std::stringify!(AOSP_LATVIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_LATVIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-mk"))
)]
wordlist! {
    ident : AOSP_MACEDONIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_macedonian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("mk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/mk_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-mk")))]
///The
#[doc = ::std::stringify!(AOSP_MACEDONIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MACEDONIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-mlym", feature = "lang-ml"))
)]
wordlist! {
    ident : AOSP_MALAYALAM, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_malayalam"), script :
    Some(std::borrow::Cow::Borrowed("Mlym")), language :
    Some(std::borrow::Cow::Borrowed("ml")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ml_Mlym.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-mlym", feature = "lang-ml")))]
///The
#[doc = ::std::stringify!(AOSP_MALAYALAM)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MALAYALAM: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-mn"))
)]
wordlist! {
    ident : AOSP_MONGOLIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_mongolian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("mn")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/mn_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-mn")))]
///The
#[doc = ::std::stringify!(AOSP_MONGOLIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MONGOLIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-deva", feature = "lang-mr"))
)]
wordlist! {
    ident : AOSP_MARATHI_DEVANAGARI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_marathi_devanagari"), script :
    Some(std::borrow::Cow::Borrowed("Deva")), language :
    Some(std::borrow::Cow::Borrowed("mr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/mr_Deva.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-deva", feature = "lang-mr")))]
///The
#[doc = ::std::stringify!(AOSP_MARATHI_DEVANAGARI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MARATHI_DEVANAGARI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "aosp", feature = "lang-ms")))]
wordlist! {
    ident : AOSP_MALAY, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_malay"), script : None, language :
    Some(std::borrow::Cow::Borrowed("ms")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ms.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "lang-ms")))]
///The
#[doc = ::std::stringify!(AOSP_MALAY)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_MALAY: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-mymr", feature = "lang-my"))
)]
wordlist! {
    ident : AOSP_BURMESE_MYANMAR, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_burmese_myanmar"), script :
    Some(std::borrow::Cow::Borrowed("Mymr")), language :
    Some(std::borrow::Cow::Borrowed("my")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/my_Mymr.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-mymr", feature = "lang-my")))]
///The
#[doc = ::std::stringify!(AOSP_BURMESE_MYANMAR)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_BURMESE_MYANMAR: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-nb"))
)]
wordlist! {
    ident : AOSP_NORWEGIAN_BOKMÅL_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_norwegian_bokmål_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("nb")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/nb_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-nb")))]
///The
#[doc = ::std::stringify!(AOSP_NORWEGIAN_BOKMÅL_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_NORWEGIAN_BOKMÅL_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-deva", feature = "lang-ne"))
)]
wordlist! {
    ident : AOSP_NEPALI_DEVANAGARI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_nepali_devanagari"), script :
    Some(std::borrow::Cow::Borrowed("Deva")), language :
    Some(std::borrow::Cow::Borrowed("ne")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ne_Deva.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-deva", feature = "lang-ne")))]
///The
#[doc = ::std::stringify!(AOSP_NEPALI_DEVANAGARI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_NEPALI_DEVANAGARI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-nl"))
)]
wordlist! {
    ident : AOSP_DUTCH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_dutch_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("nl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/nl_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-nl")))]
///The
#[doc = ::std::stringify!(AOSP_DUTCH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_DUTCH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-orya", feature = "lang-or"))
)]
wordlist! {
    ident : AOSP_ORIYA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_oriya"), script :
    Some(std::borrow::Cow::Borrowed("Orya")), language :
    Some(std::borrow::Cow::Borrowed("or")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/or_Orya.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-orya", feature = "lang-or")))]
///The
#[doc = ::std::stringify!(AOSP_ORIYA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ORIYA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-guru", feature = "lang-pa"))
)]
wordlist! {
    ident : AOSP_PANJABI_GURMUKHI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_panjabi_gurmukhi"), script :
    Some(std::borrow::Cow::Borrowed("Guru")), language :
    Some(std::borrow::Cow::Borrowed("pa")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/pa_Guru.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-guru", feature = "lang-pa")))]
///The
#[doc = ::std::stringify!(AOSP_PANJABI_GURMUKHI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_PANJABI_GURMUKHI: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-pl"))
)]
wordlist! {
    ident : AOSP_POLISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_polish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("pl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/pl_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-pl")))]
///The
#[doc = ::std::stringify!(AOSP_POLISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_POLISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-pt"))
)]
wordlist! {
    ident : AOSP_PORTUGUESE_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_portuguese_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("pt")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/pt_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-pt")))]
///The
#[doc = ::std::stringify!(AOSP_PORTUGUESE_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_PORTUGUESE_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-rm"))
)]
wordlist! {
    ident : AOSP_ROMANSH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_romansh_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("rm")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/rm_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-rm")))]
///The
#[doc = ::std::stringify!(AOSP_ROMANSH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ROMANSH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-ro"))
)]
wordlist! {
    ident : AOSP_ROMANIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_romanian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("ro")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ro_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-ro")))]
///The
#[doc = ::std::stringify!(AOSP_ROMANIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ROMANIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-ru"))
)]
wordlist! {
    ident : AOSP_RUSSIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_russian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("ru")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ru_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-ru")))]
///The
#[doc = ::std::stringify!(AOSP_RUSSIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_RUSSIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-sinh", feature = "lang-si"))
)]
wordlist! {
    ident : AOSP_SINHALA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_sinhala"), script :
    Some(std::borrow::Cow::Borrowed("Sinh")), language :
    Some(std::borrow::Cow::Borrowed("si")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/si_Sinh.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-sinh", feature = "lang-si")))]
///The
#[doc = ::std::stringify!(AOSP_SINHALA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SINHALA: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sk"))
)]
wordlist! {
    ident : AOSP_SLOVAK_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_slovak_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sk_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sk")))]
///The
#[doc = ::std::stringify!(AOSP_SLOVAK_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SLOVAK_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sl"))
)]
wordlist! {
    ident : AOSP_SLOVENIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_slovenian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sl_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sl")))]
///The
#[doc = ::std::stringify!(AOSP_SLOVENIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SLOVENIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sq"))
)]
wordlist! {
    ident : AOSP_ALBANIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_albanian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sq")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sq_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sq")))]
///The
#[doc = ::std::stringify!(AOSP_ALBANIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ALBANIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-sr"))
)]
wordlist! {
    ident : AOSP_SERBIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_serbian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("sr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sr_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-sr")))]
///The
#[doc = ::std::stringify!(AOSP_SERBIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SERBIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sr"))
)]
wordlist! {
    ident : AOSP_SERBIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_serbian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sr_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sr")))]
///The
#[doc = ::std::stringify!(AOSP_SERBIAN_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SERBIAN_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sv"))
)]
wordlist! {
    ident : AOSP_SWEDISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_swedish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sv")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sv_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sv")))]
///The
#[doc = ::std::stringify!(AOSP_SWEDISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SWEDISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-sw"))
)]
wordlist! {
    ident : AOSP_SWAHILI_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_swahili_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sw")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sw_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-sw")))]
///The
#[doc = ::std::stringify!(AOSP_SWAHILI_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_SWAHILI_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-taml", feature = "lang-ta"))
)]
wordlist! {
    ident : AOSP_TAMIL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_tamil"), script :
    Some(std::borrow::Cow::Borrowed("Taml")), language :
    Some(std::borrow::Cow::Borrowed("ta")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ta_Taml.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-taml", feature = "lang-ta")))]
///The
#[doc = ::std::stringify!(AOSP_TAMIL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_TAMIL: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-telu", feature = "lang-te"))
)]
wordlist! {
    ident : AOSP_TELUGU, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_telugu"), script :
    Some(std::borrow::Cow::Borrowed("Telu")), language :
    Some(std::borrow::Cow::Borrowed("te")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/te_Telu.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-telu", feature = "lang-te")))]
///The
#[doc = ::std::stringify!(AOSP_TELUGU)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_TELUGU: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-thai", feature = "lang-th"))
)]
wordlist! {
    ident : AOSP_THAI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_thai"), script :
    Some(std::borrow::Cow::Borrowed("Thai")), language :
    Some(std::borrow::Cow::Borrowed("th")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/th_Thai.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-thai", feature = "lang-th")))]
///The
#[doc = ::std::stringify!(AOSP_THAI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_THAI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "aosp", feature = "lang-tl")))]
wordlist! {
    ident : AOSP_TAGALOG, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_tagalog"), script : None, language :
    Some(std::borrow::Cow::Borrowed("tl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/tl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "lang-tl")))]
///The
#[doc = ::std::stringify!(AOSP_TAGALOG)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_TAGALOG: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-tr"))
)]
wordlist! {
    ident : AOSP_TURKISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_turkish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("tr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/tr_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-tr")))]
///The
#[doc = ::std::stringify!(AOSP_TURKISH_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_TURKISH_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-cyrl", feature = "lang-uk"))
)]
wordlist! {
    ident : AOSP_UKRAINIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_ukrainian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("uk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/uk_Cyrl.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-cyrl", feature = "lang-uk")))]
///The
#[doc = ::std::stringify!(AOSP_UKRAINIAN_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_UKRAINIAN_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-arab", feature = "lang-ur"))
)]
wordlist! {
    ident : AOSP_URDU_ARABIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_urdu_arabic"), script :
    Some(std::borrow::Cow::Borrowed("Arab")), language :
    Some(std::borrow::Cow::Borrowed("ur")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ur_Arab.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-arab", feature = "lang-ur")))]
///The
#[doc = ::std::stringify!(AOSP_URDU_ARABIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_URDU_ARABIC: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-uz"))
)]
wordlist! {
    ident : AOSP_UZBEK_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_uzbek_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("uz")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/uz_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-uz")))]
///The
#[doc = ::std::stringify!(AOSP_UZBEK_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_UZBEK_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-vi"))
)]
wordlist! {
    ident : AOSP_VIETNAMESE_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_vietnamese_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("vi")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/vi_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-vi")))]
///The
#[doc = ::std::stringify!(AOSP_VIETNAMESE_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_VIETNAMESE_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-hani", feature = "lang-zh"))
)]
wordlist! {
    ident : AOSP_CHINESE_HAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_chinese_han"), script :
    Some(std::borrow::Cow::Borrowed("Hani")), language :
    Some(std::borrow::Cow::Borrowed("zh")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/zh_Hani.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-hani", feature = "lang-zh")))]
///The
#[doc = ::std::stringify!(AOSP_CHINESE_HAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_CHINESE_HAN: crate::WordList = crate::WordList::stub();
#[cfg(
    all(not(docsrs), any(feature = "aosp", feature = "script-latn", feature = "lang-zu"))
)]
wordlist! {
    ident : AOSP_ZULU_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_zulu_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("zu")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/zu_Latn.txt",
    ".br")),
}
#[cfg(all(docsrs, any(feature = "aosp", feature = "script-latn", feature = "lang-zu")))]
///The
#[doc = ::std::stringify!(AOSP_ZULU_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static AOSP_ZULU_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-adlm")))]
wordlist! {
    ident : DIFFENATOR_ADLAM, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_adlam"), script :
    Some(std::borrow::Cow::Borrowed("Adlm")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Adlam.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-adlm")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ADLAM)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ADLAM: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-arab")))]
wordlist! {
    ident : DIFFENATOR_ARABIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_arabic"), script :
    Some(std::borrow::Cow::Borrowed("Arab")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Arabic.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-arab")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ARABIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ARABIC: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-armn")))]
wordlist! {
    ident : DIFFENATOR_ARMENIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_armenian"), script :
    Some(std::borrow::Cow::Borrowed("Armn")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Armenian.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-armn")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ARMENIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ARMENIAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-avst")))]
wordlist! {
    ident : DIFFENATOR_AVESTAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_avestan"), script :
    Some(std::borrow::Cow::Borrowed("Avst")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Avestan.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-avst")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_AVESTAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_AVESTAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-beng")))]
wordlist! {
    ident : DIFFENATOR_BENGALI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_bengali"), script :
    Some(std::borrow::Cow::Borrowed("Beng")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Bengali.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-beng")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_BENGALI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_BENGALI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-bopo")))]
wordlist! {
    ident : DIFFENATOR_BOPOMOFO, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_bopomofo"), script :
    Some(std::borrow::Cow::Borrowed("Bopo")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Bopomofo.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-bopo")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_BOPOMOFO)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_BOPOMOFO: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-cans")))]
wordlist! {
    ident : DIFFENATOR_CANADIAN_ABORIGINAL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_canadian_aboriginal"), script :
    Some(std::borrow::Cow::Borrowed("Cans")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Canadian_Aboriginal.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-cans")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_CANADIAN_ABORIGINAL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_CANADIAN_ABORIGINAL: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-cakm")))]
wordlist! {
    ident : DIFFENATOR_CHAKMA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_chakma"), script :
    Some(std::borrow::Cow::Borrowed("Cakm")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Chakma.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-cakm")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_CHAKMA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_CHAKMA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-cher")))]
wordlist! {
    ident : DIFFENATOR_CHEROKEE, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_cherokee"), script :
    Some(std::borrow::Cow::Borrowed("Cher")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Cherokee.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-cher")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_CHEROKEE)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_CHEROKEE: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-zyyy")))]
wordlist! {
    ident : DIFFENATOR_COMMON, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_common"), script :
    Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Common.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-zyyy")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_COMMON)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_COMMON: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-cyrl")))]
wordlist! {
    ident : DIFFENATOR_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Cyrillic.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-cyrl")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_CYRILLIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_CYRILLIC: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-deva")))]
wordlist! {
    ident : DIFFENATOR_DEVANAGARI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_devanagari"), script :
    Some(std::borrow::Cow::Borrowed("Deva")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Devanagari.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-deva")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_DEVANAGARI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_DEVANAGARI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-ethi")))]
wordlist! {
    ident : DIFFENATOR_ETHIOPIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_ethiopic"), script :
    Some(std::borrow::Cow::Borrowed("Ethi")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Ethiopic.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-ethi")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ETHIOPIC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ETHIOPIC: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-geor")))]
wordlist! {
    ident : DIFFENATOR_GEORGIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_georgian"), script :
    Some(std::borrow::Cow::Borrowed("Geor")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Georgian.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-geor")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_GEORGIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_GEORGIAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-grek")))]
wordlist! {
    ident : DIFFENATOR_GREEK, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_greek"), script :
    Some(std::borrow::Cow::Borrowed("Grek")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Greek.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-grek")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_GREEK)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_GREEK: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-gujr")))]
wordlist! {
    ident : DIFFENATOR_GUJARATI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_gujarati"), script :
    Some(std::borrow::Cow::Borrowed("Gujr")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Gujarati.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-gujr")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_GUJARATI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_GUJARATI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-guru")))]
wordlist! {
    ident : DIFFENATOR_GURMUKHI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_gurmukhi"), script :
    Some(std::borrow::Cow::Borrowed("Guru")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Gurmukhi.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-guru")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_GURMUKHI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_GURMUKHI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-hebr")))]
wordlist! {
    ident : DIFFENATOR_HEBREW, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_hebrew"), script :
    Some(std::borrow::Cow::Borrowed("Hebr")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Hebrew.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-hebr")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_HEBREW)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_HEBREW: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-hira")))]
wordlist! {
    ident : DIFFENATOR_HIRAGANA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_hiragana"), script :
    Some(std::borrow::Cow::Borrowed("Hira")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Hiragana.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-hira")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_HIRAGANA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_HIRAGANA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-jpan")))]
wordlist! {
    ident : DIFFENATOR_JAPANESE, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_japanese"), script :
    Some(std::borrow::Cow::Borrowed("Jpan")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Japanese.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-jpan")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_JAPANESE)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_JAPANESE: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-kana")))]
wordlist! {
    ident : DIFFENATOR_KATAKANA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_katakana"), script :
    Some(std::borrow::Cow::Borrowed("Kana")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Katakana.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-kana")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_KATAKANA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_KATAKANA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-khmr")))]
wordlist! {
    ident : DIFFENATOR_KHMER, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_khmer"), script :
    Some(std::borrow::Cow::Borrowed("Khmr")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Khmer.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-khmr")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_KHMER)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_KHMER: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-laoo")))]
wordlist! {
    ident : DIFFENATOR_LAO, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_lao"), script :
    Some(std::borrow::Cow::Borrowed("Laoo")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Lao.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-laoo")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_LAO)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_LAO: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-latn")))]
wordlist! {
    ident : DIFFENATOR_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Latin.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-latn")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_LATIN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_LATIN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-lisu")))]
wordlist! {
    ident : DIFFENATOR_LISU, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_lisu"), script :
    Some(std::borrow::Cow::Borrowed("Lisu")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Lisu.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-lisu")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_LISU)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_LISU: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-mlym")))]
wordlist! {
    ident : DIFFENATOR_MALAYALAM, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_malayalam"), script :
    Some(std::borrow::Cow::Borrowed("Mlym")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Malayalam.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-mlym")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_MALAYALAM)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_MALAYALAM: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-mong")))]
wordlist! {
    ident : DIFFENATOR_MONGOLIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_mongolian"), script :
    Some(std::borrow::Cow::Borrowed("Mong")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Mongolian.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-mong")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_MONGOLIAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_MONGOLIAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-mymr")))]
wordlist! {
    ident : DIFFENATOR_MYANMAR, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_myanmar"), script :
    Some(std::borrow::Cow::Borrowed("Mymr")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Myanmar.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-mymr")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_MYANMAR)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_MYANMAR: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-olck")))]
wordlist! {
    ident : DIFFENATOR_OL_CHIKI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_ol_chiki"), script :
    Some(std::borrow::Cow::Borrowed("Olck")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Ol_Chiki.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-olck")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_OL_CHIKI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_OL_CHIKI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-orya")))]
wordlist! {
    ident : DIFFENATOR_ORIYA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_oriya"), script :
    Some(std::borrow::Cow::Borrowed("Orya")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Oriya.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-orya")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_ORIYA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_ORIYA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-osge")))]
wordlist! {
    ident : DIFFENATOR_OSAGE, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_osage"), script :
    Some(std::borrow::Cow::Borrowed("Osge")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Osage.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-osge")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_OSAGE)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_OSAGE: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-sinh")))]
wordlist! {
    ident : DIFFENATOR_SINHALA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_sinhala"), script :
    Some(std::borrow::Cow::Borrowed("Sinh")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Sinhala.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-sinh")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_SINHALA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_SINHALA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-syrc")))]
wordlist! {
    ident : DIFFENATOR_SYRIAC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_syriac"), script :
    Some(std::borrow::Cow::Borrowed("Syrc")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Syriac.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-syrc")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_SYRIAC)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_SYRIAC: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-taml")))]
wordlist! {
    ident : DIFFENATOR_TAMIL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_tamil"), script :
    Some(std::borrow::Cow::Borrowed("Taml")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Tamil.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-taml")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_TAMIL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_TAMIL: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-telu")))]
wordlist! {
    ident : DIFFENATOR_TELUGU, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_telugu"), script :
    Some(std::borrow::Cow::Borrowed("Telu")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Telugu.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-telu")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_TELUGU)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_TELUGU: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-thai")))]
wordlist! {
    ident : DIFFENATOR_THAI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_thai"), script :
    Some(std::borrow::Cow::Borrowed("Thai")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Thai.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-thai")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_THAI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_THAI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-thaa")))]
wordlist! {
    ident : DIFFENATOR_THANAA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_thanaa"), script :
    Some(std::borrow::Cow::Borrowed("Thaa")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Thanaa.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-thaa")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_THANAA)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_THANAA: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-tibt")))]
wordlist! {
    ident : DIFFENATOR_TIBETAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_tibetan"), script :
    Some(std::borrow::Cow::Borrowed("Tibt")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Tibetan.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-tibt")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_TIBETAN)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_TIBETAN: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-tfng")))]
wordlist! {
    ident : DIFFENATOR_TIFINAGH, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_tifinagh"), script :
    Some(std::borrow::Cow::Borrowed("Tfng")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Tifinagh.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-tfng")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_TIFINAGH)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_TIFINAGH: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "diffenator", feature = "script-vaii")))]
wordlist! {
    ident : DIFFENATOR_VAI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_vai"), script :
    Some(std::borrow::Cow::Borrowed("Vaii")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Vai.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "diffenator", feature = "script-vaii")))]
///The
#[doc = ::std::stringify!(DIFFENATOR_VAI)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static DIFFENATOR_VAI: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "ucd", feature = "script-zyyy")))]
wordlist! {
    ident : UCD_EMOJI_ALL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("ucd_emoji_all"), script :
    Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "ucd/Emoji_All.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "ucd", feature = "script-zyyy")))]
///The
#[doc = ::std::stringify!(UCD_EMOJI_ALL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static UCD_EMOJI_ALL: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "ucd", feature = "script-zyyy")))]
wordlist! {
    ident : UCD_EMOJI_COLOR, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("ucd_emoji_color"), script :
    Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "ucd/Emoji_Color.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "ucd", feature = "script-zyyy")))]
///The
#[doc = ::std::stringify!(UCD_EMOJI_COLOR)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static UCD_EMOJI_COLOR: crate::WordList = crate::WordList::stub();
#[cfg(all(not(docsrs), any(feature = "ucd", feature = "script-zyyy")))]
wordlist! {
    ident : UCD_EMOJI_TEXTUAL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("ucd_emoji_textual"), script :
    Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "ucd/Emoji_Textual.txt", ".br")),
}
#[cfg(all(docsrs, any(feature = "ucd", feature = "script-zyyy")))]
///The
#[doc = ::std::stringify!(UCD_EMOJI_TEXTUAL)]
/**word list.

Compiled into the binary compressed with Brotli, decompressed at runtime.*/
pub static UCD_EMOJI_TEXTUAL: crate::WordList = crate::WordList::stub();
