// @generated by cargo xtask slwl
#[rustfmt::skip]
wordlist! {
    ident : AOSP_AFRIKAANS_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_afrikaans_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("af")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/af_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-af",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_AMHARIC_ETHIOPIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_amharic_ethiopic"), script :
    Some(std::borrow::Cow::Borrowed("Ethi")), language :
    Some(std::borrow::Cow::Borrowed("am")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/am_Ethi.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-ethi", feature
    = "lang-am",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ARABIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_arabic"), script :
    Some(std::borrow::Cow::Borrowed("Arab")), language :
    Some(std::borrow::Cow::Borrowed("ar")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ar_Arab.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-arab", feature
    = "lang-ar",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ASSAMESE_BENGALI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_assamese_bengali"), script :
    Some(std::borrow::Cow::Borrowed("Beng")), language :
    Some(std::borrow::Cow::Borrowed("as")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/as_Beng.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-beng", feature
    = "lang-as",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_AZERBAIJANI_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_azerbaijani_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("az")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/az_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-az",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_BELARUSIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_belarusian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("be")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/be_Cyrl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-cyrl", feature
    = "lang-be",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_BELARUSIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_belarusian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("be")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/be_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-be",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_BULGARIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_bulgarian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("bg")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/bg_Cyrl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-cyrl", feature
    = "lang-bg",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_BENGALI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_bengali"), script :
    Some(std::borrow::Cow::Borrowed("Beng")), language :
    Some(std::borrow::Cow::Borrowed("bn")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/bn_Beng.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-beng", feature
    = "lang-bn",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_BOSNIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_bosnian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("bs")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/bs_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-bs",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_CATALAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_catalan_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("ca")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ca_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-ca",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_CZECH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_czech_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("cs")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/cs_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-cs",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_DANISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_danish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("da")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/da_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-da",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_GERMAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_german_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("de")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/de_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-de",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_MODERN_GREEK, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_modern_greek"), script :
    Some(std::borrow::Cow::Borrowed("Grek")), language :
    Some(std::borrow::Cow::Borrowed("el")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/el_Grek.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-grek", feature
    = "lang-el",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ENGLISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_english_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("en")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/en_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-en",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_SPANISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_spanish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("es")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/es_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-es",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ESTONIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_estonian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("et")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/et_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-et",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_BASQUE_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_basque_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("eu")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/eu_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-eu",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_PERSIAN_ARABIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_persian_arabic"), script :
    Some(std::borrow::Cow::Borrowed("Arab")), language :
    Some(std::borrow::Cow::Borrowed("fa")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/fa_Arab.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-arab", feature
    = "lang-fa",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_FINNISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_finnish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("fi")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/fi_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-fi",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_FRENCH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_french_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("fr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/fr_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-fr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_GALICIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_galician_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("gl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/gl_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-gl",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_GUJARATI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_gujarati"), script :
    Some(std::borrow::Cow::Borrowed("Gujr")), language :
    Some(std::borrow::Cow::Borrowed("gu")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/gu_Gujr.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-gujr", feature
    = "lang-gu",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_HINDI_DEVANAGARI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_hindi_devanagari"), script :
    Some(std::borrow::Cow::Borrowed("Deva")), language :
    Some(std::borrow::Cow::Borrowed("hi")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hi_Deva.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-deva", feature
    = "lang-hi",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_HINDI_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_hindi_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("hi")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hi_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-hi",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_CROATIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_croatian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("hr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hr_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-hr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_HUNGARIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_hungarian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("hu")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hu_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-hu",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ARMENIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_armenian"), script :
    Some(std::borrow::Cow::Borrowed("Armn")), language :
    Some(std::borrow::Cow::Borrowed("hy")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/hy_Armn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-armn", feature
    = "lang-hy",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ICELANDIC_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_icelandic_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("is")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/is_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-is",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ITALIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_italian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("it")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/it_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-it",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_JAPANESE_HIRAGANA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_japanese_hiragana"), script :
    Some(std::borrow::Cow::Borrowed("Hira")), language :
    Some(std::borrow::Cow::Borrowed("ja")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ja_Hira.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-hira", feature
    = "lang-ja",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_JAPANESE_KATAKANA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_japanese_katakana"), script :
    Some(std::borrow::Cow::Borrowed("Kana")), language :
    Some(std::borrow::Cow::Borrowed("ja")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ja_Kana.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-kana", feature
    = "lang-ja",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_GEORGIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_georgian"), script :
    Some(std::borrow::Cow::Borrowed("Geor")), language :
    Some(std::borrow::Cow::Borrowed("ka")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ka_Geor.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-geor", feature
    = "lang-ka",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_KAZAKH_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kazakh_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("kk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/kk_Cyrl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-cyrl", feature
    = "lang-kk",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_KAZAKH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kazakh_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("kk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/kk_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-kk",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_CENTRAL_KHMER, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_central_khmer"), script :
    Some(std::borrow::Cow::Borrowed("Khmr")), language :
    Some(std::borrow::Cow::Borrowed("km")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/km_Khmr.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-khmr", feature
    = "lang-km",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_KANNADA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kannada"), script :
    Some(std::borrow::Cow::Borrowed("Knda")), language :
    Some(std::borrow::Cow::Borrowed("kn")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/kn_Knda.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-knda", feature
    = "lang-kn",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_KOREAN_HANGUL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_korean_hangul"), script :
    Some(std::borrow::Cow::Borrowed("Hang")), language :
    Some(std::borrow::Cow::Borrowed("ko")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ko_Hang.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-hang", feature
    = "lang-ko",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_KIRGHIZ_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kirghiz_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("ky")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ky_Cyrl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-cyrl", feature
    = "lang-ky",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_KIRGHIZ_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_kirghiz_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("ky")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ky_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-ky",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_LAO, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_lao"), script :
    Some(std::borrow::Cow::Borrowed("Laoo")), language :
    Some(std::borrow::Cow::Borrowed("lo")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/lo_Laoo.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-laoo", feature
    = "lang-lo",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_LITHUANIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_lithuanian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("lt")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/lt_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-lt",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_LATVIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_latvian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("lv")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/lv_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-lv",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_MACEDONIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_macedonian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("mk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/mk_Cyrl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-cyrl", feature
    = "lang-mk",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_MALAYALAM, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_malayalam"), script :
    Some(std::borrow::Cow::Borrowed("Mlym")), language :
    Some(std::borrow::Cow::Borrowed("ml")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ml_Mlym.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-mlym", feature
    = "lang-ml",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_MONGOLIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_mongolian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("mn")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/mn_Cyrl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-cyrl", feature
    = "lang-mn",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_MARATHI_DEVANAGARI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_marathi_devanagari"), script :
    Some(std::borrow::Cow::Borrowed("Deva")), language :
    Some(std::borrow::Cow::Borrowed("mr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/mr_Deva.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-deva", feature
    = "lang-mr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_MALAY, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_malay"), script : None, language :
    Some(std::borrow::Cow::Borrowed("ms")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ms.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "lang-ms",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_BURMESE_MYANMAR, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_burmese_myanmar"), script :
    Some(std::borrow::Cow::Borrowed("Mymr")), language :
    Some(std::borrow::Cow::Borrowed("my")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/my_Mymr.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-mymr", feature
    = "lang-my",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_NORWEGIAN_BOKMÅL_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_norwegian_bokmål_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("nb")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/nb_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-nb",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_NEPALI_DEVANAGARI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_nepali_devanagari"), script :
    Some(std::borrow::Cow::Borrowed("Deva")), language :
    Some(std::borrow::Cow::Borrowed("ne")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ne_Deva.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-deva", feature
    = "lang-ne",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_DUTCH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_dutch_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("nl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/nl_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-nl",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ORIYA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_oriya"), script :
    Some(std::borrow::Cow::Borrowed("Orya")), language :
    Some(std::borrow::Cow::Borrowed("or")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/or_Orya.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-orya", feature
    = "lang-or",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_PANJABI_GURMUKHI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_panjabi_gurmukhi"), script :
    Some(std::borrow::Cow::Borrowed("Guru")), language :
    Some(std::borrow::Cow::Borrowed("pa")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/pa_Guru.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-guru", feature
    = "lang-pa",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_POLISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_polish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("pl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/pl_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-pl",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_PORTUGUESE_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_portuguese_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("pt")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/pt_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-pt",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ROMANSH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_romansh_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("rm")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/rm_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-rm",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ROMANIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_romanian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("ro")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ro_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-ro",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_RUSSIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_russian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("ru")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ru_Cyrl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-cyrl", feature
    = "lang-ru",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_SINHALA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_sinhala"), script :
    Some(std::borrow::Cow::Borrowed("Sinh")), language :
    Some(std::borrow::Cow::Borrowed("si")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/si_Sinh.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-sinh", feature
    = "lang-si",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_SLOVAK_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_slovak_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sk_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-sk",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_SLOVENIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_slovenian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sl_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-sl",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ALBANIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_albanian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sq")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sq_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-sq",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_SERBIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_serbian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("sr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sr_Cyrl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-cyrl", feature
    = "lang-sr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_SERBIAN_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_serbian_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sr_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-sr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_SWEDISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_swedish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sv")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sv_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-sv",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_SWAHILI_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_swahili_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("sw")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/sw_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-sw",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_TAMIL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_tamil"), script :
    Some(std::borrow::Cow::Borrowed("Taml")), language :
    Some(std::borrow::Cow::Borrowed("ta")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ta_Taml.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-taml", feature
    = "lang-ta",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_TELUGU, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_telugu"), script :
    Some(std::borrow::Cow::Borrowed("Telu")), language :
    Some(std::borrow::Cow::Borrowed("te")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/te_Telu.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-telu", feature
    = "lang-te",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_THAI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_thai"), script :
    Some(std::borrow::Cow::Borrowed("Thai")), language :
    Some(std::borrow::Cow::Borrowed("th")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/th_Thai.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-thai", feature
    = "lang-th",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_TAGALOG, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_tagalog"), script : None, language :
    Some(std::borrow::Cow::Borrowed("tl")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/tl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "lang-tl",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_TURKISH_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_turkish_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("tr")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/tr_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-tr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_UKRAINIAN_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_ukrainian_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language :
    Some(std::borrow::Cow::Borrowed("uk")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/uk_Cyrl.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-cyrl", feature
    = "lang-uk",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_URDU_ARABIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_urdu_arabic"), script :
    Some(std::borrow::Cow::Borrowed("Arab")), language :
    Some(std::borrow::Cow::Borrowed("ur")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/ur_Arab.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-arab", feature
    = "lang-ur",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_UZBEK_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_uzbek_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("uz")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/uz_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-uz",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_VIETNAMESE_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_vietnamese_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("vi")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/vi_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-vi",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_CHINESE_HAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_chinese_han"), script :
    Some(std::borrow::Cow::Borrowed("Hani")), language :
    Some(std::borrow::Cow::Borrowed("zh")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/zh_Hani.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-hani", feature
    = "lang-zh",))],
}
#[rustfmt::skip]
wordlist! {
    ident : AOSP_ZULU_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("aosp_zulu_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language :
    Some(std::borrow::Cow::Borrowed("zu")), }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/', "aosp/zu_Latn.txt",
    ".br")), features_attr : #[cfg(any(feature = "aosp", feature = "script-latn", feature
    = "lang-zu",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_ADLAM, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_adlam"), script :
    Some(std::borrow::Cow::Borrowed("Adlm")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Adlam.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-adlm",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_ARABIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_arabic"), script :
    Some(std::borrow::Cow::Borrowed("Arab")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Arabic.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-arab",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_ARMENIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_armenian"), script :
    Some(std::borrow::Cow::Borrowed("Armn")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Armenian.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-armn",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_AVESTAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_avestan"), script :
    Some(std::borrow::Cow::Borrowed("Avst")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Avestan.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-avst",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_BENGALI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_bengali"), script :
    Some(std::borrow::Cow::Borrowed("Beng")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Bengali.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-beng",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_BOPOMOFO, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_bopomofo"), script :
    Some(std::borrow::Cow::Borrowed("Bopo")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Bopomofo.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-bopo",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_CANADIAN_ABORIGINAL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_canadian_aboriginal"), script :
    Some(std::borrow::Cow::Borrowed("Cans")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Canadian_Aboriginal.txt", ".br")), features_attr : #[cfg(any(feature =
    "diffenator", feature = "script-cans",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_CHAKMA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_chakma"), script :
    Some(std::borrow::Cow::Borrowed("Cakm")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Chakma.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-cakm",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_CHEROKEE, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_cherokee"), script :
    Some(std::borrow::Cow::Borrowed("Cher")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Cherokee.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-cher",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_COMMON, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_common"), script :
    Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Common.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-zyyy",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_CYRILLIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_cyrillic"), script :
    Some(std::borrow::Cow::Borrowed("Cyrl")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Cyrillic.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-cyrl",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_DEVANAGARI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_devanagari"), script :
    Some(std::borrow::Cow::Borrowed("Deva")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Devanagari.txt", ".br")), features_attr : #[cfg(any(feature =
    "diffenator", feature = "script-deva",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_ETHIOPIC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_ethiopic"), script :
    Some(std::borrow::Cow::Borrowed("Ethi")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Ethiopic.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-ethi",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_GEORGIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_georgian"), script :
    Some(std::borrow::Cow::Borrowed("Geor")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Georgian.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-geor",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_GREEK, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_greek"), script :
    Some(std::borrow::Cow::Borrowed("Grek")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Greek.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-grek",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_GUJARATI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_gujarati"), script :
    Some(std::borrow::Cow::Borrowed("Gujr")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Gujarati.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-gujr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_GURMUKHI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_gurmukhi"), script :
    Some(std::borrow::Cow::Borrowed("Guru")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Gurmukhi.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-guru",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_HEBREW, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_hebrew"), script :
    Some(std::borrow::Cow::Borrowed("Hebr")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Hebrew.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-hebr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_HIRAGANA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_hiragana"), script :
    Some(std::borrow::Cow::Borrowed("Hira")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Hiragana.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-hira",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_JAPANESE, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_japanese"), script :
    Some(std::borrow::Cow::Borrowed("Jpan")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Japanese.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-jpan",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_KATAKANA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_katakana"), script :
    Some(std::borrow::Cow::Borrowed("Kana")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Katakana.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-kana",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_KHMER, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_khmer"), script :
    Some(std::borrow::Cow::Borrowed("Khmr")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Khmer.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-khmr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_LAO, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_lao"), script :
    Some(std::borrow::Cow::Borrowed("Laoo")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Lao.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-laoo",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_LATIN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_latin"), script :
    Some(std::borrow::Cow::Borrowed("Latn")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Latin.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-latn",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_LISU, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_lisu"), script :
    Some(std::borrow::Cow::Borrowed("Lisu")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Lisu.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-lisu",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_MALAYALAM, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_malayalam"), script :
    Some(std::borrow::Cow::Borrowed("Mlym")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Malayalam.txt", ".br")), features_attr : #[cfg(any(feature =
    "diffenator", feature = "script-mlym",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_MONGOLIAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_mongolian"), script :
    Some(std::borrow::Cow::Borrowed("Mong")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Mongolian.txt", ".br")), features_attr : #[cfg(any(feature =
    "diffenator", feature = "script-mong",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_MYANMAR, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_myanmar"), script :
    Some(std::borrow::Cow::Borrowed("Mymr")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Myanmar.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-mymr",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_OL_CHIKI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_ol_chiki"), script :
    Some(std::borrow::Cow::Borrowed("Olck")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Ol_Chiki.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-olck",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_ORIYA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_oriya"), script :
    Some(std::borrow::Cow::Borrowed("Orya")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Oriya.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-orya",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_OSAGE, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_osage"), script :
    Some(std::borrow::Cow::Borrowed("Osge")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Osage.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-osge",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_SINHALA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_sinhala"), script :
    Some(std::borrow::Cow::Borrowed("Sinh")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Sinhala.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-sinh",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_SYRIAC, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_syriac"), script :
    Some(std::borrow::Cow::Borrowed("Syrc")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Syriac.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-syrc",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_TAMIL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_tamil"), script :
    Some(std::borrow::Cow::Borrowed("Taml")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Tamil.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-taml",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_TELUGU, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_telugu"), script :
    Some(std::borrow::Cow::Borrowed("Telu")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Telugu.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-telu",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_THAI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_thai"), script :
    Some(std::borrow::Cow::Borrowed("Thai")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Thai.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-thai",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_THANAA, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_thanaa"), script :
    Some(std::borrow::Cow::Borrowed("Thaa")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Thanaa.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-thaa",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_TIBETAN, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_tibetan"), script :
    Some(std::borrow::Cow::Borrowed("Tibt")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Tibetan.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-tibt",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_TIFINAGH, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_tifinagh"), script :
    Some(std::borrow::Cow::Borrowed("Tfng")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Tifinagh.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-tfng",))],
}
#[rustfmt::skip]
wordlist! {
    ident : DIFFENATOR_VAI, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("diffenator_vai"), script :
    Some(std::borrow::Cow::Borrowed("Vaii")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "diffenator/Vai.txt", ".br")), features_attr : #[cfg(any(feature = "diffenator",
    feature = "script-vaii",))],
}
#[rustfmt::skip]
wordlist! {
    ident : UCD_EMOJI_ALL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("ucd_emoji_all"), script :
    Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "ucd/Emoji_All.txt", ".br")), features_attr : #[cfg(any(feature = "ucd", feature =
    "script-zyyy",))],
}
#[rustfmt::skip]
wordlist! {
    ident : UCD_EMOJI_COLOR, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("ucd_emoji_color"), script :
    Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "ucd/Emoji_Color.txt", ".br")), features_attr : #[cfg(any(feature = "ucd", feature =
    "script-zyyy",))],
}
#[rustfmt::skip]
wordlist! {
    ident : UCD_EMOJI_TEXTUAL, metadata : crate ::WordListMetadata { name :
    ::std::borrow::Cow::Borrowed("ucd_emoji_textual"), script :
    Some(std::borrow::Cow::Borrowed("Zyyy")), language : None, }, bytes :
    ::std::include_bytes!(::std::concat!(::std::env!("OUT_DIR"), '/',
    "ucd/Emoji_Textual.txt", ".br")), features_attr : #[cfg(any(feature = "ucd", feature
    = "script-zyyy",))],
}

