[project]
name = "fontheight"
dynamic = [
    "version",
    "readme",
    "description",
    "authors",
    "license"
]
requires-python = ">=3.8"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
profile = "release"
locked = true
