on:
  release:
    types: [created]

jobs:
  fontheight-cli:
    if: contains(github.ref, 'refs/tags/fontheight-cli-v')
    runs-on: ${{ matrix.os.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - build: linux
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: macos-m1
            os: macos-latest
            target: aarch64-apple-darwin

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v5
      - name: Build (release mode)
        run: cargo build --release --target ${{ matrix.os.target }}
      - name: Create binary archive
      - name: Attach archive to release
